doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'App\Domaining\Migrations': '%kernel.project_dir%/vendor/domaining/domain/migrations'
        'App\Retailing\Migrations': '%kernel.project_dir%/vendor/retailing/retail/migrations'
        'App\Carting\Migrations': '%kernel.project_dir%/vendor/carting/cart/migrations'
        'App\Cataloging\Migrations': '%kernel.project_dir%/vendor/cataloging/catalog/migrations'
        'App\Vendoring\Migrations': '%kernel.project_dir%/vendor/vendoring/vendor/migrations'
        'App\Paging\Migrations': '%kernel.project_dir%/../Paging/migrations'
        'App\Walleting\Migrations': '%kernel.project_dir%/vendor/smartresponsor/walleting/migrations'
    enable_profiler: false

when@dev:
    doctrine_migrations:
        migrations_paths:
            # namespace is arbitrary but should be different from App\Migrations
            # as migrations classes should NOT be autoloaded
            'App\Domaining\Migrations': '%kernel.project_dir%/vendor/domaining/domain/migrations'
            'App\Retailing\Migrations': '%kernel.project_dir%/vendor/retailing/retail/migrations'
            'App\Carting\Migrations': '%kernel.project_dir%/vendor/carting/cart/migrations'
            'App\Cataloging\Migrations': '%kernel.project_dir%/../Cataloging/migrations'
            'App\Vendoring\Migrations': '%kernel.project_dir%/vendor/vendoring/vendor/migrations'
            'App\Administering\Migrations': '%kernel.project_dir%/../Administering/migrations'
            'App\Commercializing\Migrations': '%kernel.project_dir%/../Commercializing/migrations'
            'App\Exchanging\Migrations': '%kernel.project_dir%/../Exchanging/migrations'
            'App\Tagging\Migrations': '%kernel.project_dir%/../Tagging/migrations'
            'App\Commissioning\Migrations': '%kernel.project_dir%/../Commissioning/migrations'
            'App\Paging\Migrations': '%kernel.project_dir%/../Paging/migrations'
            'App\Walleting\Migrations': '%kernel.project_dir%/vendor/smartresponsor/walleting/migrations'
