parameters:
    app.platform_data_database_default: 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8'
    app.object_review_database_default: 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app_review?serverVersion=16&charset=utf8'
    app.platform_system_database_default: 'sqlite:///%kernel.project_dir%/var/platform_system.sqlite'

doctrine:
    dbal:
        default_connection: postgres
        types:
            ltree: App\Cataloging\Doctrine\Type\LtreeType
        connections:
            postgres:
                url: '%env(default:app.platform_data_database_default:PLATFORM_DATA_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
                mapping_types:
                    ltree: ltree
            review:
                url: '%env(default:app.object_review_database_default:OBJECT_REVIEW_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
            sqlite:
                driver: 'pdo_sqlite'
                path: '%kernel.project_dir%/var/platform_system.sqlite'
                server_version: '3.21'
                charset: utf8mb4
                profiling_collect_backtrace: '%kernel.debug%'

    orm:
        default_entity_manager: postgres
        resolve_target_entities:
            App\Taxating\Interface\Order\OrderTaxationInterface: App\Taxating\Entity\Taxation\TaxationOrderEntity
            App\Taxating\EntityInterface\Taxation\Order\OrderTaxationInterface: App\Taxating\Entity\Taxation\TaxationOrderEntity
            App\Taxating\Interface\Taxation\TaxationCategoryInterface: App\Taxating\Entity\Taxation\TaxationCategoryEntity
            App\Taxating\EntityInterface\Taxation\TaxationCategoryInterface: App\Taxating\Entity\Taxation\TaxationCategoryEntity
            App\Taxating\Interface\Taxation\TaxationRateInterface: App\Taxating\Entity\Taxation\TaxationRateEntity
            App\Taxating\EntityInterface\Taxation\TaxationRateInterface: App\Taxating\Entity\Taxation\TaxationRateEntity
            App\Taxating\Interface\Taxation\TaxationZoneInterface: App\Taxating\Entity\Taxation\TaxationZoneEntity
            App\Taxating\EntityInterface\Taxation\TaxationZoneInterface: App\Taxating\Entity\Taxation\TaxationZoneEntity
            App\Taxating\EntityInterface\Taxation\TaxationTaxSummaryInterface: App\Taxating\Entity\Taxation\TaxationTaxSummaryEntity
            App\Taxating\EntityInterface\Taxation\TaxationRateValueInterface: App\Taxating\Entity\Taxation\TaxationValueEntity
            App\Taxating\EntityInterface\Taxation\CertificateEntityInterface: App\Taxating\Entity\Taxation\TaxationCertificateEntity
            App\Taxating\EntityInterface\Taxation\OutboxEntityInterface: App\Taxating\Entity\Taxation\TaxationOutboxEntity
            App\Taxating\EntityInterface\Taxation\RegistrationEntityInterface: App\Taxating\Entity\Taxation\TaxationRegistrationEntity
            App\Cataloging\EntityInterface\CategoryInterface: App\Cataloging\Entity\CatalogCategoryEntity
        entity_managers:
            postgres:
                connection: postgres
                auto_mapping: false
                validate_xml_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Accessing:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/accessing/access/src/Entity'
                        prefix: 'App\Accessing\Entity'
                        alias: Accessing
                    Vendoring:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/vendoring/vendor/src/Entity/Vendor'
                        prefix: 'App\Vendoring\Entity\Vendor'
                        alias: Vendoring
                    Localizing:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/localizing/locale/src/Entity'
                        prefix: 'App\Localizing\Entity'
                        alias: Localizing
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
                    Carting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/carting/cart/src/Entity'
                        prefix: 'App\Carting\Entity'
                        alias: Carting
                    Attaching:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/attaching/attachment/src/Entity'
                        prefix: 'App\Attaching\Entity'
                        alias: Attaching
                    Cataloging:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/cataloging/catalog/src/Entity/Catalog'
                        prefix: 'App\Cataloging\Entity\Catalog'
                        alias: Cataloging
                    Paging:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/paging/page/src/Entity'
                        prefix: 'App\Paging\Entity'
                        alias: Paging
            review:
                connection: review
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
            sqlite:
                connection: sqlite
                auto_mapping: false
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
            system:
                connection: sqlite
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Administering:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/administering/administration/src/Entity'
                        prefix: 'App\Administering\Entity'
                        alias: Administering
