doctrine:
    dbal:
        default_connection: user_data
        connections:
            user_data:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
            app_data:
                url: '%env(resolve:APP_DATA_DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'

    orm:
        default_entity_manager: user_data
        entity_managers:
            user_data:
                connection: user_data
                auto_mapping: false
                validate_xml_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Applicating:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Applicating\Entity'
                        alias: Applicating
