parameters:
    app.platform_data_database_default: '%env(DATABASE_URL)%'
    app.object_review_database_default: '%env(DATABASE_URL)%'
    app.platform_system_database_default: 'sqlite:///%kernel.project_dir%/var/data/platform_system.sqlite'

doctrine:
    dbal:
        default_connection: postgres
        types:
            ltree: App\Cataloging\Doctrine\Type\LtreeType
        connections:
            postgres:
                url: '%env(default:app.platform_data_database_default:PLATFORM_DATA_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
                mapping_types:
                    ltree: ltree
            review:
                url: '%env(default:app.object_review_database_default:OBJECT_REVIEW_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
            sqlite:
                driver: 'pdo_sqlite'
                path: '%kernel.project_dir%/var/platform_system.sqlite'
                server_version: '3.21'
                charset: utf8mb4
                profiling_collect_backtrace: '%kernel.debug%'

    orm:
        default_entity_manager: postgres
        resolve_target_entities:
            App\Taxating\Interface\Order\OrderTaxationInterface: App\Taxating\Entity\Taxation\TaxationOrderEntity
            App\Taxating\EntityInterface\Taxation\Order\OrderTaxationInterface: App\Taxating\Entity\Taxation\TaxationOrderEntity
            App\Taxating\Interface\Taxation\TaxationCategoryInterface: App\Taxating\Entity\Taxation\TaxationCategoryEntity
            App\Taxating\EntityInterface\Taxation\TaxationCategoryInterface: App\Taxating\Entity\Taxation\TaxationCategoryEntity
            App\Taxating\Interface\Taxation\TaxationRateInterface: App\Taxating\Entity\Taxation\TaxationRateEntity
            App\Taxating\EntityInterface\Taxation\TaxationRateInterface: App\Taxating\Entity\Taxation\TaxationRateEntity
            App\Taxating\Interface\Taxation\TaxationZoneInterface: App\Taxating\Entity\Taxation\TaxationZoneEntity
            App\Taxating\EntityInterface\Taxation\TaxationZoneInterface: App\Taxating\Entity\Taxation\TaxationZoneEntity
            App\Taxating\EntityInterface\Taxation\TaxationTaxSummaryInterface: App\Taxating\Entity\Taxation\TaxationTaxSummaryEntity
            App\Taxating\EntityInterface\Taxation\TaxationRateValueInterface: App\Taxating\Entity\Taxation\TaxationValueEntity
            App\Taxating\EntityInterface\Taxation\CertificateEntityInterface: App\Taxating\Entity\Taxation\TaxationCertificateEntity
            App\Taxating\EntityInterface\Taxation\OutboxEntityInterface: App\Taxating\Entity\Taxation\TaxationOutboxEntity
            App\Taxating\EntityInterface\Taxation\RegistrationEntityInterface: App\Taxating\Entity\Taxation\TaxationRegistrationEntity
            App\Cataloging\EntityInterface\CategoryInterface: App\Cataloging\Entity\CatalogCategoryEntity
        entity_managers:
            postgres:
                connection: postgres
                auto_mapping: false
                validate_xml_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Domaining:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/domaining/domain/src/Entity'
                        prefix: 'App\Domaining\Entity'
                        alias: Domaining
                    Vendoring:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/vendoring/vendor/src/Entity/Vendor'
                        prefix: 'App\Vendoring\Entity\Vendor'
                        alias: Vendoring
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
                    Carting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/carting/cart/src/Entity'
                        prefix: 'App\Carting\Entity'
                        alias: Carting
                    Casing:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/casing/case/src/Entity'
                        prefix: 'App\Casing\Entity'
                        alias: Casing
                    Retailing:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/retailing/retail/src/Entity'
                        prefix: 'App\Retailing\Entity'
                        alias: Retailing
                    Relating:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/relating/relation/src/Entity'
                        prefix: 'App\Entity'
                        alias: Relating
                    Ordering:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/ordering/order/src/Entity'
                        prefix: 'App\Ordering\Entity'
                        alias: Ordering
                    Shipping:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/shipping/shipment/src/Entity'
                        prefix: 'App\Shipping\Entity'
                        alias: Shipping
                    Paying:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/paying/payment/src/Entity'
                        prefix: 'App\Paying\Entity'
                        alias: Paying
                    Walleting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/smartresponsor/walleting/src/Entity'
                        prefix: 'App\Walleting\Entity'
                        alias: Walleting
            review:
                connection: review
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
            sqlite:
                connection: sqlite
                auto_mapping: false
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
            system:
                connection: sqlite
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
