doctrine:
    dbal:
        default_connection: postgres
        types:
            ltree: App\Cataloging\Doctrine\Type\LtreeType
        connections:
            postgres:
                url: '%env(resolve:PLATFORM_DATA_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
                mapping_types:
                    ltree: ltree
            review:
                url: '%env(resolve:OBJECT_REVIEW_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
            sqlite:
                url: '%env(resolve:PLATFORM_SYSTEM_DATABASE)%'
                driver: 'pdo_sqlite'
                server_version: '3.21'
                charset: utf8mb4
                profiling_collect_backtrace: '%kernel.debug%'

    orm:
        default_entity_manager: postgres
        resolve_target_entities:
            App\Taxating\Interface\Order\OrderTaxationInterface: App\Taxating\Entity\Taxation\TaxationOrderEntity
            App\Taxating\EntityInterface\Taxation\Order\OrderTaxationInterface: App\Taxating\Entity\Taxation\TaxationOrderEntity
            App\Taxating\Interface\Taxation\TaxationCategoryInterface: App\Taxating\Entity\Taxation\TaxationCategoryEntity
            App\Taxating\EntityInterface\Taxation\TaxationCategoryInterface: App\Taxating\Entity\Taxation\TaxationCategoryEntity
            App\Taxating\Interface\Taxation\TaxationRateInterface: App\Taxating\Entity\Taxation\TaxationRateEntity
            App\Taxating\EntityInterface\Taxation\TaxationRateInterface: App\Taxating\Entity\Taxation\TaxationRateEntity
            App\Taxating\Interface\Taxation\TaxationZoneInterface: App\Taxating\Entity\Taxation\TaxationZoneEntity
            App\Taxating\EntityInterface\Taxation\TaxationZoneInterface: App\Taxating\Entity\Taxation\TaxationZoneEntity
            App\Taxating\EntityInterface\Taxation\TaxationTaxSummaryInterface: App\Taxating\Entity\Taxation\TaxationTaxSummaryEntity
            App\Taxating\EntityInterface\Taxation\TaxationRateValueInterface: App\Taxating\Entity\Taxation\TaxationValueEntity
            App\Taxating\EntityInterface\Taxation\CertificateEntityInterface: App\Taxating\Entity\Taxation\TaxationCertificateEntity
            App\Taxating\EntityInterface\Taxation\OutboxEntityInterface: App\Taxating\Entity\Taxation\TaxationOutboxEntity
            App\Taxating\EntityInterface\Taxation\RegistrationEntityInterface: App\Taxating\Entity\Taxation\TaxationRegistrationEntity
            App\Cataloging\EntityInterface\CategoryInterface: App\Cataloging\Entity\CatalogCategoryEntity
        entity_managers:
            postgres:
                connection: postgres
                auto_mapping: false
                validate_xml_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/../Objecting/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
            review:
                connection: review
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/../Objecting/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
                    Review:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Review'
                        prefix: 'App\Entity\Review'
                        alias: Review
            sqlite:
                connection: sqlite
                auto_mapping: false
                mappings:
                    Objecting:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/../Objecting/src/Embeddable'
                        prefix: 'App\Objecting\Embeddable'
                        alias: Objecting
                    Module:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Module'
                        prefix: 'App\Entity\Module'
                        alias: Module
                    Category:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category
                    Menu:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Menu'
                        prefix: 'App\Entity\Menu'
                        alias: Menu
                    Featured:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Featured'
                        prefix: 'App\Entity\Featured'
                        alias: Featured
                    ProjectType:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: ProjectType
                    ProductType:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: ProductType
            system:
                connection: sqlite
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
