doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'App\Domaining\Migrations': '%kernel.project_dir%/vendor/domaining/domain/migrations'
        'App\Retailing\Migrations': '%kernel.project_dir%/vendor/retailing/retail/migrations'
        'App\Carting\Migrations': '%kernel.project_dir%/vendor/carting/cart/migrations'
        'App\Cataloging\Migrations': '%kernel.project_dir%/vendor/cataloging/catalog/migrations'
        'App\Vendoring\Migrations': '%kernel.project_dir%/vendor/vendoring/vendor/migrations'
        'App\Paging\Migrations': '%kernel.project_dir%/../Paging/migrations'
        'App\Walleting\Migrations': '%kernel.project_dir%/vendor/smartresponsor/walleting/migrations'
    enable_profiler: false

when@dev:
    doctrine_migrations:
        migrations_paths:
            # namespace is arbitrary but should be different from App\Migrations
            # as migrations classes should NOT be autoloaded
            'App\Domaining\Migrations': '%kernel.project_dir%/vendor/domaining/domain/migrations'
            'App\Retailing\Migrations': '%kernel.project_dir%/vendor/retailing/retail/migrations'
            'App\Carting\Migrations': '%kernel.project_dir%/vendor/carting/cart/migrations'
            'App\Cataloging\Migrations': '%kernel.project_dir%/../Cataloging/migrations'
            'App\Vendoring\Migrations': '%kernel.project_dir%/vendor/vendoring/vendor/migrations'
            # Administering currently owns no Doctrine migrations.
            # Commercializing currently owns no available Doctrine migrations.
            # Exchanging currently owns no available Doctrine migrations.
            # Tagging currently owns no available Doctrine migrations.
            # Commissioning currently owns no available Doctrine migrations.
            'App\Paging\Migrations': '%kernel.project_dir%/../Paging/migrations'
            'App\Walleting\Migrations': '%kernel.project_dir%/vendor/smartresponsor/walleting/migrations'
            'App\Messaging\Migrations\Baseline': '%kernel.project_dir%/../Messaging/migrations/baseline'
            'App\Notifying\Migrations\Baseline': '%kernel.project_dir%/../Notifying/migrations/baseline'
