managing:
  left_menu:
    - analysing
    - applicating
    - attaching
    - billing
    - cataloging
    - commissioning
    - currencing
    - exchanging
    - messaging
    - ordering
    - paging
    - paying
    - walleting
    - shipping
    - subscripting
    - tagging
    - taxating
    - vendoring

when@prod:
  managing:
    left_menu:
      - analysing
      - applicating
      - attaching
      - billing
      - cataloging
      - commissioning
      - currencing
      - exchanging
      - messaging
      - ordering
      - paging
      - paying
      - walleting
      - shipping
      - subscripting
      - tagging
      - taxating
      - vendoring
