navigation:
    schema: 3
    shell_groups:
        workspace:
            label: Workspace
            location: shell.left.middle
            type: menu
            priority: 10
            items:
                workspace:
                    type: link
                    label: Workspace
                    icon: workspace
                    priority: 10
                    target:
                        type: path
                        path: /
    runtime_roles:
        fallback_roles:
            - ROLE_USER
