<?php

declare(strict_types=1);

return [
    'schema' => 'app.kernel.runtime_scope.v1',
    'scope' => 'prod-runtime-lock',
    'source' => 'operator runtime decision validated against composer.prod.json production inventory',
    'sourceComposerFile' => 'composer.prod.json',
    'strict' => true,
    'enabledBundles' => [
        App\Cruding\CrudingBundle::class,
        App\Viewing\ViewingBundle::class,
        App\Accessing\AccessingBundle::class,
        App\Attaching\AttachingBundle::class,
        App\Cataloging\CatalogingBundle::class,
        App\Interfacing\InterfacingBundle::class,
        App\Navigating\NavigatingBundle::class,
        App\Managing\ManagingBundle::class,
        App\Paging\PageBundle::class,
        App\Retailing\RetailingBundle::class,
        App\Ordering\OrderingBundle::class,
        App\Shipping\ShipmentBundle::class,
        App\Paying\PayingBundle::class,
        App\Vendoring\VendoringBundle::class,
        App\Walleting\WalletingBundle::class,
        App\Rolling\RollingBundle::class,
        App\Localizing\LocalizingBundle::class,
        App\Delivering\DeliveringBundle::class,
        App\Domaining\DomainingBundle::class,
    ],
    'scope' => [
        'accessing',
        'attaching',
        'cataloging',
        'cruding',
        'interfacing',
        'localizing',
        'managing',
        'navigating',
        'paging',
        'ordering',
        'paying',
        'retailing',
        'shipping',
        'rolling',
        'vendoring',
        'walleting',
        'viewing',
        'domaining',
    ],
    'entity' => [
        'access',
        'application',
        'domain',
        'attachment',
        'catalog',
        'category',
        'media',
        'product',
        'retail',
        'order',
        'shipment',
        'payment',
        'role',
        'search',
        'vendor',
        'wallet',
        'account',
        'reservation',
        'funding',
        'withdrawal',
        'payment-instrument',
    ],
    'packages' => [
        'accessing/access',
        'attaching/attachment',
        'cataloging/catalog',
        'cruding/crud',
        'domaining/domain',
        'interfacing/interface',
        'localizing/locale',
        'managing/manage',
        'navigating/navigation',
        'paging/page',
        'ordering/order',
        'retailing/retail',
        'shipping/shipment',
        'paying/payment',
        'rolling/role',
        'vendoring/vendor',
        'viewing/view',
        'smartresponsor/walleting',
    ],
    'disabledComponents' => [
        'analysing',
        'billing',
        'carting',
        'commissioning',
        'exchanging',
        'indexing',
        'merchandising',
        'messaging',
        'projecting',
        'subscripting',
        'taxating',
    ],
];
