<?php

declare(strict_types=1);

namespace App\Service\Interfacing\Crud\Contribution;

use App\Interfacing\Contribution\Crud\InterfaceAbstractCrudResourceContribution;
use App\Interfacing\ContributionInterface\Crud\InterfaceCrudResourceDescriptorContributionInterface;

final class EcosystemCrudResourceContributionService extends InterfaceAbstractCrudResourceContribution implements InterfaceCrudResourceDescriptorContributionInterface
{
    public function provide(): array
    {
        return [
            // Long-tail Smart Response resources. Component-specific contributions win over these planned entries.
            $this->genericResource('accessing.account', 'Accessing', 'Account', 'account', 'Planned fallback entry; the Accessing contribution should be preferred when present.'),
            $this->genericResource('accessing.session', 'Accessing', 'Session', 'session', 'Planned fallback entry; the Accessing contribution should be preferred when present.'),
            $this->genericResource('accessing.security-event', 'Accessing', 'Security event', 'security-event', 'Planned fallback entry; the Accessing contribution should be preferred when present.'),
            $this->genericResource('adjudicating.adjudication', 'Adjudicating', 'Adjudication', 'adjudication', 'Planned canonical CRUD resource for the Adjudicating/Adjudication component.'),
            $this->genericResource('analysing.analytics-report', 'Analysing', 'Analytics report', 'analytics-report', 'Planned canonical CRUD resource for analysis/report screens.'),
            $this->genericResource('anchoring.anchor', 'Anchoring', 'Anchor', 'anchor', 'Planned canonical CRUD resource for Anchoring.'),
            $this->genericResource('applicating.application', 'Applicating', 'Application', 'application', 'Planned fallback entry; the Applicating contribution should be preferred when present.'),
            $this->genericResource('applicating.release', 'Applicating', 'Release', 'release', 'Planned fallback entry; the Applicating contribution should be preferred when present.'),
            $this->genericResource('attaching.attachment', 'Attaching', 'Attachment', 'attachment', 'Planned canonical CRUD resource for uploaded/linked files.'),
            $this->genericResource('billing.invoice', 'Billing', 'Invoice', 'invoice', 'Planned fallback entry; the Billing contribution should be preferred when present.'),
            $this->genericResource('billing.meter', 'Billing', 'Meter', 'meter', 'Planned fallback entry; the Billing contribution should be preferred when present.'),
            $this->genericResource('bridging.bridge', 'Bridging', 'Bridge', 'bridge', 'Planned canonical CRUD resource for integration bridges.'),
            $this->genericResource('cataloging.category', 'Cataloging', 'Category', 'category', 'Planned fallback entry; the Cataloging contribution should be preferred when present.'),
            $this->genericResource('cataloging.collection', 'Cataloging', 'Collection', 'collection', 'Planned fallback entry; the Cataloging contribution should be preferred when present.'),
            $this->genericResource('cataloging.product', 'Cataloging', 'Product', 'product', 'E-commerce product index/form surface.'),
            $this->genericResource('cataloging.attribute', 'Cataloging', 'Attribute', 'attribute', 'E-commerce product attribute surface.'),
            $this->genericResource('commercializing.offer', 'Commercializing', 'Commercial offer', 'commercial-offer', 'Commercial offer surface for storefront and campaign workflows.'),
            $this->genericResource('complying.case', 'Complying', 'Compliance case', 'compliance-case', 'Planned canonical CRUD resource for compliance work.'),
            $this->genericResource('consuming.consumption', 'Consuming', 'Consumption', 'consumption', 'Planned canonical CRUD resource for consumption records.'),
            $this->genericResource('discovering.discovery', 'Discovering', 'Discovery', 'discovery', 'Planned canonical CRUD resource for discovery screens.'),
            $this->genericResource('configuring.configuration', 'Configuring', 'Configuration', 'configuration', 'Configuration screens need immediate CRUD visibility for host setup.'),
            $this->genericResource('couponing.coupon', 'Couponing', 'Coupon', 'coupon', 'Coupon CRUD path prepares promotion/discount workflows.'),
            $this->genericResource('couponing.coupon-redemption', 'Couponing', 'Coupon redemption', 'coupon-redemption', 'Redemption records provide audit visibility for coupon usage.'),
            $this->genericResource('exporting.export-job', 'Exporting', 'Export job', 'export-job', 'Export job CRUD frames expose operator export status.'),
            $this->genericResource('fulfilling.fulfillment', 'Fulfilling', 'Fulfillment', 'fulfillment', 'Fulfillment CRUD path complements order and shipment flows.'),
            $this->genericResource('importing.import-job', 'Importing', 'Import job', 'import-job', 'Import job CRUD frames expose intake status and retries.'),
            $this->genericResource('inventorying.inventory-item', 'Inventorying', 'Inventory item', 'inventory-item', 'Inventory item screens support stock review and manual correction.'),
            $this->genericResource('inventorying.stock-movement', 'Inventorying', 'Stock movement', 'stock-movement', 'Stock movement rows need show/edit/delete probes for audit flows.'),
            $this->genericResource('notifying.notification-template', 'Notifying', 'Notification template', 'notification-template', 'Notification template CRUD path prepares messaging and event notices.'),
            $this->genericResource('pricing.price-rule', 'Pricing', 'Price rule', 'price-rule', 'Price rule screens support storefront and B2B pricing workflows.'),
            $this->genericResource('pricing.price-list', 'Pricing', 'Price list', 'price-list', 'Price list CRUD path gives operators a familiar index/edit surface.'),
            $this->genericResource('promoting.promotion', 'Promoting', 'Promotion', 'promotion', 'Promotion CRUD path supports campaign setup.'),
            $this->genericResource('quoting.quote', 'Quoting', 'Quote', 'quote', 'Quote CRUD path supports pre-order commercial workflows.'),
            $this->genericResource('reporting.report', 'Reporting', 'Report', 'report', 'Report CRUD path provides admin-visible report definitions.'),
            $this->genericResource('reviewing.review', 'Reviewing', 'Review', 'review', 'Review CRUD path gives moderation screens a canonical route surface.'),
            $this->genericResource('scheduling.schedule', 'Scheduling', 'Schedule', 'schedule', 'Schedule CRUD path prepares calendar/workflow controls.'),
            $this->genericResource('subscribing.subscription', 'Subscribing', 'Subscription', 'subscription', 'Subscription CRUD path supports recurring commercial flows.'),
            $this->genericResource('synchronizing.sync-job', 'Synchronizing', 'Sync job', 'sync-job', 'Sync job CRUD frames expose external integration state.'),
            $this->genericResource('documenting.document', 'Documenting', 'Document', 'document', 'Normalized Documenting component entry; replaces the previous Documentating spelling.'),
            $this->genericResource('evaluating.evaluation', 'Evaluating', 'Evaluation', 'evaluation', 'Planned canonical CRUD resource for evaluation workflows.'),
            $this->genericResource('faceting.facet', 'Faceting', 'Facet', 'facet', 'Product discovery/filtering facet surface.'),
            $this->genericResource('facting.fact', 'Facting', 'Fact', 'fact', 'Planned canonical CRUD resource for fact records.'),
            $this->genericResource('governancing.policy', 'Governancing', 'Governance policy', 'governance-policy', 'Planned canonical CRUD resource for governance policy screens.'),
            $this->genericResource('harvesting.harvest', 'Harvesting', 'Harvest', 'harvest', 'Planned canonical CRUD resource for Harvesting outputs.'),
            $this->genericResource('indexing.record', 'Indexing', 'Index record', 'index-record', 'Search/index maintenance surface.'),
            $this->genericResource('locating.location', 'Locating', 'Location', 'location', 'Planned canonical CRUD resource for location records.'),
            $this->genericResource('messaging.message', 'Messaging', 'Message', 'message', 'Planned fallback entry; the Messaging contribution should be preferred when present.'),
            $this->genericResource('messaging.room', 'Messaging', 'Room', 'room', 'Planned fallback entry; the Messaging contribution should be preferred when present.'),
            $this->genericResource('messaging.thread', 'Messaging', 'Thread', 'thread', 'Planned fallback entry; the Messaging contribution should be preferred when present.'),
            $this->genericResource('messaging.notification', 'Messaging', 'Notification', 'notification', 'Planned fallback entry; the Messaging contribution should be preferred when present.'),
            $this->genericResource('messaging.digest', 'Messaging', 'Digest', 'digest', 'Planned fallback entry; the Messaging contribution should be preferred when present.'),
            $this->genericResource('ordering.cart', 'Ordering', 'Cart', 'cart', 'E-commerce cart/checkout session surface.'),
            $this->genericResource('ordering.checkout-session', 'Ordering', 'Checkout session', 'checkout-session', 'E-commerce checkout flow surface.'),
            $this->genericResource('ordering.order', 'Ordering', 'Order', 'order', 'Planned fallback entry; the Ordering contribution should be preferred when present.'),
            $this->genericResource('ordering.order-item', 'Ordering', 'Order item', 'order-item', 'Planned fallback entry; the Ordering contribution should be preferred when present.'),
            $this->genericResource('ordering.return', 'Ordering', 'Return', 'return', 'E-commerce return/cancellation surface.'),
            $this->genericResource('paying.payment', 'Paying', 'Payment', 'payment', 'Payment operation surface.'),
            $this->genericResource('paying.refund', 'Paying', 'Refund', 'refund', 'Refund operation surface.'),
            $this->genericResource('projecting.projection', 'Projecting', 'Projection', 'projection', 'Planned canonical CRUD resource for projections.'),
            $this->genericResource('retailing.offer', 'Retailing', 'Retail offer', 'retail-offer', 'Retail/public offer surface.'),
            $this->genericResource('retailing.price-book', 'Retailing', 'Price book', 'price-book', 'E-commerce price-book surface.'),
            $this->genericResource('rolling.rollout', 'Rolling', 'Rollout', 'rollout', 'Planned canonical CRUD resource for rollout controls.'),
            $this->genericResource('runtiming.status', 'Runtiming', 'Runtime status', 'runtime-status', 'Runtime/operator status surface.'),
            $this->genericResource('search.query', 'Search', 'Search query', 'search-query', 'Search request/query surface.'),
            $this->genericResource('shipping.carrier', 'Shipping', 'Carrier', 'carrier', 'Shipping carrier setup surface.'),
            $this->genericResource('shipping.label', 'Shipping', 'Label', 'label', 'Shipping label surface.'),
            $this->genericResource('shipping.shipment', 'Shipping', 'Shipment', 'shipment', 'Planned canonical CRUD resource for shipments.'),
            $this->genericResource('shipping.tracking-event', 'Shipping', 'Tracking event', 'tracking-event', 'Tracking event surface.'),
            $this->genericResource('tagging.tag', 'Tagging', 'Tag', 'tag', 'Tagging surface for catalog/search linkage.'),
            $this->genericResource('taxating.api', 'Taxating', 'Taxation API', 'taxation-api', 'Planned fallback entry; the Taxating contribution should be preferred when present.'),
            $this->genericResource('taxating.rate', 'Taxating', 'Taxation rate', 'taxation-rate', 'Planned fallback entry; the Taxating contribution should be preferred when present.'),
            $this->genericResource('taxating.zone', 'Taxating', 'Taxation zone', 'taxation-zone', 'Planned fallback entry; the Taxating contribution should be preferred when present.'),
            $this->genericResource('taxating.rate-value', 'Taxating', 'Taxation rate value', 'taxation-rate-value', 'Planned fallback entry; the Taxating contribution should be preferred when present.'),
            $this->genericResource('taxating.product-taxation', 'Taxating', 'Product taxation', 'product-taxation', 'Planned fallback entry; the Taxating contribution should be preferred when present.'),
            $this->genericResource('taxating.en-use', 'Taxating', 'EN Use', 'taxation-en-use', 'Planned fallback entry; the Taxating contribution should be preferred when present.'),
            $this->genericResource('vendoring.vendor', 'Vendoring', 'Vendor', 'vendor', 'Planned fallback entry; the Vendoring contribution should be preferred when present.'),
            $this->genericResource('vendoring.vendor-transaction', 'Vendoring', 'Vendor transaction', 'vendor-transaction', 'Planned fallback entry; the Vendoring contribution should be preferred when present.'),
            $this->genericResource('vendoring.vendor-profile', 'Vendoring', 'Vendor profile', 'vendor-profile', 'Planned fallback entry; the Vendoring contribution should be preferred when present.'),
            $this->genericResource('vendoring.payout', 'Vendoring', 'Payout', 'payout', 'Planned fallback entry; the Vendoring contribution should be preferred when present.'),
            $this->genericResource('vendoring.payout-account', 'Vendoring', 'Payout account', 'payout-account', 'Planned fallback entry; the Vendoring contribution should be preferred when present.'),
        ];
    }
}
