<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519011200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore analytics_alert_rule table for Analysing admin list after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS analytics_alert_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(190) NOT NULL, name VARCHAR(255) NOT NULL, condition JSON NOT NULL, channels JSON NOT NULL, is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_alert_rule_code ON analytics_alert_rule (code)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_alert_rule_active ON analytics_alert_rule (is_active)');

        foreach ([
            ['revenue-drop', 'Revenue Drop Alert', '{"metric":"revenue","operator":"lt","threshold":5000,"window":"24h"}', '["email","slack"]', true],
            ['conversion-fall', 'Checkout Conversion Alert', '{"metric":"conversion_rate","operator":"lt","threshold":0.02,"window":"12h"}', '["email"]', true],
            ['refund-spike', 'Refund Spike Alert', '{"metric":"refund_rate","operator":"gt","threshold":0.08,"window":"6h"}', '["email","pagerduty"]', true],
            ['inventory-slowdown', 'Inventory Slowdown Alert', '{"metric":"inventory_turnover","operator":"lt","threshold":1.5,"window":"48h"}', '["slack"]', false],
        ] as [$code, $name, $condition, $channels, $active]) {
            $this->addSql(
                'INSERT INTO analytics_alert_rule (code, name, condition, channels, is_active, created_at, updated_at)
                 SELECT :code, :name, :condition::json, :channels::json, ' . ($active ? 'true' : 'false') . ', NOW(), NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM analytics_alert_rule WHERE code = :code
                 )',
                [
                    'code' => $code,
                    'name' => $name,
                    'condition' => $condition,
                    'channels' => $channels,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS analytics_alert_rule');
    }
}
