<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519011400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore core Ordering tables after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, number VARCHAR(64) NOT NULL, currency VARCHAR(3) NOT NULL, grand_total NUMERIC(12, 2) NOT NULL, paid_total NUMERIC(12, 2) NOT NULL, refunded_total NUMERIC(12, 2) NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, discount_total NUMERIC(12, 2) NOT NULL, tax_total NUMERIC(12, 2) NOT NULL, status VARCHAR(32) NOT NULL, customer_id VARCHAR(64) DEFAULT NULL, vendor_id VARCHAR(64) DEFAULT NULL, tracking_code VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_orders_slug ON orders (slug)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_orders_number ON orders (number)');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT DEFAULT NULL, sku VARCHAR(128) NOT NULL, quantity INT NOT NULL, base_price NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, discount INT NOT NULL DEFAULT 0, tax INT NOT NULL DEFAULT 0, final_price INT NOT NULL DEFAULT 0, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_item_order_id ON order_item (order_id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT DEFAULT NULL, gateway VARCHAR(32) NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, external_ref VARCHAR(64) DEFAULT NULL, is_partial BOOLEAN NOT NULL, status VARCHAR(32) NOT NULL, refunded_amount NUMERIC(12, 2) NOT NULL, captured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_payment_order_id ON order_payment (order_id)');
        $this->addSql('ALTER TABLE order_payment ADD CONSTRAINT fk_order_payment_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, reason VARCHAR(128) DEFAULT NULL, is_partial BOOLEAN NOT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_refund_order_id ON order_refund (order_id)');
        $this->addSql('ALTER TABLE order_refund ADD CONSTRAINT fk_order_refund_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_shipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, carrier VARCHAR(24) NOT NULL, tracking_code VARCHAR(64) DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, status VARCHAR(24) NOT NULL, shipped_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_shipment_order_id ON order_shipment (order_id)');
        $this->addSql('ALTER TABLE order_shipment ADD CONSTRAINT fk_order_shipment_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_shipment_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shipment_id INT NOT NULL, order_item_id INT DEFAULT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_shipment_item_shipment ON order_shipment_item (shipment_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_shipment_item_order_item ON order_shipment_item (order_item_id)');
        $this->addSql('ALTER TABLE order_shipment_item ADD CONSTRAINT fk_order_shipment_item_shipment FOREIGN KEY (shipment_id) REFERENCES order_shipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_shipment_item ADD CONSTRAINT fk_order_shipment_item_order_item FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, previous_status VARCHAR(32) NOT NULL, new_status VARCHAR(32) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON order_status_history (order_id)');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_payment_allocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payment_id INT NOT NULL, order_item_id INT DEFAULT NULL, amount NUMERIC(12, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_payment_allocation_payment ON order_payment_allocation (payment_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_order_payment_allocation_order_item ON order_payment_allocation (order_item_id)');
        $this->addSql('ALTER TABLE order_payment_allocation ADD CONSTRAINT fk_order_payment_allocation_payment FOREIGN KEY (payment_id) REFERENCES order_payment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_payment_allocation ADD CONSTRAINT fk_order_payment_allocation_order_item FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS order_event_record (event_id VARCHAR(64) NOT NULL, order_id VARCHAR(64) NOT NULL, event_name VARCHAR(128) NOT NULL, payload JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(event_id))');

        $this->addSql('CREATE TABLE IF NOT EXISTS webhook_log (key VARCHAR(128) NOT NULL, event_type VARCHAR(128) NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(key))');

        foreach ([
            ['7f2a4d8e-1c23-4f5d-8f90-2b3c4d5e1001', 'ORD-20001', 'USD', '149.90', '149.90', '0.00', '129.90', '10.00', '10.00', 'draft', 'cust-001', 'vendor-001', null],
            ['7f2a4d8e-1c23-4f5d-8f90-2b3c4d5e1002', 'ORD-20002', 'USD', '89.00', '89.00', '0.00', '79.00', '5.00', '5.00', 'paid', 'cust-002', 'vendor-001', null],
            ['7f2a4d8e-1c23-4f5d-8f90-2b3c4d5e1003', 'ORD-20003', 'EUR', '249.00', '249.00', '0.00', '219.00', '15.00', '15.00', 'shipped', 'cust-003', 'vendor-002', 'TRK20003'],
            ['7f2a4d8e-1c23-4f5d-8f90-2b3c4d5e1004', 'ORD-20004', 'USD', '59.99', '59.99', '0.00', '49.99', '5.00', '5.00', 'completed', 'cust-004', 'vendor-003', 'TRK20004'],
        ] as [$slug, $number, $currency, $grandTotal, $paidTotal, $refundedTotal, $subtotal, $discountTotal, $taxTotal, $status, $customerId, $vendorId, $trackingCode]) {
            $this->addSql(
                'INSERT INTO orders (slug, number, currency, grand_total, paid_total, refunded_total, subtotal, discount_total, tax_total, status, customer_id, vendor_id, tracking_code, created_at, updated_at)
                 SELECT :slug, :number, :currency, :grand_total, :paid_total, :refunded_total, :subtotal, :discount_total, :tax_total, :status, :customer_id, :vendor_id, :tracking_code, NOW(), NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM orders WHERE slug = :slug
                 )',
                [
                    'slug' => $slug,
                    'number' => $number,
                    'currency' => $currency,
                    'grand_total' => $grandTotal,
                    'paid_total' => $paidTotal,
                    'refunded_total' => $refundedTotal,
                    'subtotal' => $subtotal,
                    'discount_total' => $discountTotal,
                    'tax_total' => $taxTotal,
                    'status' => $status,
                    'customer_id' => $customerId,
                    'vendor_id' => $vendorId,
                    'tracking_code' => $trackingCode,
                ]
            );
        }

        $this->addSql("INSERT INTO order_item (order_id, sku, quantity, base_price, currency, discount, tax, final_price)\n            SELECT o.id, 'SKU-BOOK-01', 2, 29.95, 'USD', 0, 0, 5990 FROM orders o WHERE o.number = 'ORD-20001' AND NOT EXISTS (SELECT 1 FROM order_item WHERE sku = 'SKU-BOOK-01')");
        $this->addSql("INSERT INTO order_item (order_id, sku, quantity, base_price, currency, discount, tax, final_price)\n            SELECT o.id, 'SKU-DIGI-01', 1, 89.00, 'USD', 0, 0, 8900 FROM orders o WHERE o.number = 'ORD-20002' AND NOT EXISTS (SELECT 1 FROM order_item WHERE sku = 'SKU-DIGI-01')");
        $this->addSql("INSERT INTO order_item (order_id, sku, quantity, base_price, currency, discount, tax, final_price)\n            SELECT o.id, 'SKU-HOOD-01', 1, 219.00, 'EUR', 0, 0, 21900 FROM orders o WHERE o.number = 'ORD-20003' AND NOT EXISTS (SELECT 1 FROM order_item WHERE sku = 'SKU-HOOD-01')");
        $this->addSql("INSERT INTO order_item (order_id, sku, quantity, base_price, currency, discount, tax, final_price)\n            SELECT o.id, 'SKU-GIFT-01', 1, 49.99, 'USD', 0, 0, 4999 FROM orders o WHERE o.number = 'ORD-20004' AND NOT EXISTS (SELECT 1 FROM order_item WHERE sku = 'SKU-GIFT-01')");

        $this->addSql("INSERT INTO order_payment (order_id, gateway, amount, currency, external_ref, is_partial, status, refunded_amount, captured_at)\n            SELECT o.id, 'stripe', 89.00, 'USD', 'pay_20002', false, 'paid', 0.00, NOW() FROM orders o WHERE o.number = 'ORD-20002' AND NOT EXISTS (SELECT 1 FROM order_payment WHERE external_ref = 'pay_20002')");
        $this->addSql("INSERT INTO order_payment (order_id, gateway, amount, currency, external_ref, is_partial, status, refunded_amount, captured_at)\n            SELECT o.id, 'paypal', 249.00, 'EUR', 'pay_20003', false, 'paid', 0.00, NOW() FROM orders o WHERE o.number = 'ORD-20003' AND NOT EXISTS (SELECT 1 FROM order_payment WHERE external_ref = 'pay_20003')");

        $this->addSql("INSERT INTO order_refund (order_id, amount, currency, reason, is_partial, refunded_at)\n            SELECT o.id, 59.99, 'USD', 'customer request', false, NOW() FROM orders o WHERE o.number = 'ORD-20004' AND NOT EXISTS (SELECT 1 FROM order_refund WHERE reason = 'customer request')");

        $this->addSql("INSERT INTO order_shipment (order_id, carrier, tracking_code, note, status, shipped_at, delivered_at)\n            SELECT o.id, 'ups', 'TRK20003', 'packed and shipped same day', 'delivered', NOW(), NOW() FROM orders o WHERE o.number = 'ORD-20003' AND NOT EXISTS (SELECT 1 FROM order_shipment WHERE tracking_code = 'TRK20003')");
        $this->addSql("INSERT INTO order_shipment (order_id, carrier, tracking_code, note, status, shipped_at, delivered_at)\n            SELECT o.id, 'fedex', 'TRK20004', 'gift order delivered', 'completed', NOW(), NOW() FROM orders o WHERE o.number = 'ORD-20004' AND NOT EXISTS (SELECT 1 FROM order_shipment WHERE tracking_code = 'TRK20004')");

        $this->addSql("INSERT INTO order_status_history (order_id, previous_status, new_status, changed_at)\n            SELECT o.id, 'draft', 'paid', NOW() FROM orders o WHERE o.number = 'ORD-20002' AND NOT EXISTS (SELECT 1 FROM order_status_history WHERE order_id = o.id AND new_status = 'paid')");
        $this->addSql("INSERT INTO order_status_history (order_id, previous_status, new_status, changed_at)\n            SELECT o.id, 'paid', 'shipped', NOW() FROM orders o WHERE o.number = 'ORD-20003' AND NOT EXISTS (SELECT 1 FROM order_status_history WHERE order_id = o.id AND new_status = 'shipped')");
        $this->addSql("INSERT INTO order_status_history (order_id, previous_status, new_status, changed_at)\n            SELECT o.id, 'shipped', 'completed', NOW() FROM orders o WHERE o.number = 'ORD-20004' AND NOT EXISTS (SELECT 1 FROM order_status_history WHERE order_id = o.id AND new_status = 'completed')");

        $this->addSql("INSERT INTO order_payment_allocation (payment_id, order_item_id, amount)\n            SELECT p.id, i.id, 89.00 FROM order_payment p INNER JOIN order_item i ON i.sku = 'SKU-DIGI-01' WHERE p.external_ref = 'pay_20002' AND NOT EXISTS (SELECT 1 FROM order_payment_allocation WHERE payment_id = p.id)");
        $this->addSql("INSERT INTO order_payment_allocation (payment_id, order_item_id, amount)\n            SELECT p.id, i.id, 249.00 FROM order_payment p INNER JOIN order_item i ON i.sku = 'SKU-HOOD-01' WHERE p.external_ref = 'pay_20003' AND NOT EXISTS (SELECT 1 FROM order_payment_allocation WHERE payment_id = p.id)");

        $this->addSql("INSERT INTO order_event_record (event_id, order_id, event_name, payload, occurred_at)\n            VALUES ('evt_order_20002', 'ORD-20002', 'order.paid', '{\"orderId\":\"ORD-20002\",\"status\":\"paid\"}'::json, NOW()) ON CONFLICT (event_id) DO NOTHING");
        $this->addSql("INSERT INTO order_event_record (event_id, order_id, event_name, payload, occurred_at)\n            VALUES ('evt_order_20003', 'ORD-20003', 'order.shipped', '{\"orderId\":\"ORD-20003\",\"status\":\"shipped\"}'::json, NOW()) ON CONFLICT (event_id) DO NOTHING");
        $this->addSql("INSERT INTO order_event_record (event_id, order_id, event_name, payload, occurred_at)\n            VALUES ('evt_order_20004', 'ORD-20004', 'order.completed', '{\"orderId\":\"ORD-20004\",\"status\":\"completed\"}'::json, NOW()) ON CONFLICT (event_id) DO NOTHING");

        $this->addSql("INSERT INTO webhook_log (key, event_type, payload) VALUES ('wh_order_20002', 'payment.captured', '{\"orderId\":\"ORD-20002\"}' ) ON CONFLICT (key) DO NOTHING");
        $this->addSql("INSERT INTO webhook_log (key, event_type, payload) VALUES ('wh_order_20003', 'shipment.delivered', '{\"orderId\":\"ORD-20003\"}' ) ON CONFLICT (key) DO NOTHING");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS webhook_log');
        $this->addSql('DROP TABLE IF EXISTS order_event_record');
        $this->addSql('DROP TABLE IF EXISTS order_payment_allocation');
        $this->addSql('DROP TABLE IF EXISTS order_status_history');
        $this->addSql('DROP TABLE IF EXISTS order_shipment_item');
        $this->addSql('DROP TABLE IF EXISTS order_shipment');
        $this->addSql('DROP TABLE IF EXISTS order_refund');
        $this->addSql('DROP TABLE IF EXISTS order_payment');
        $this->addSql('DROP TABLE IF EXISTS order_item');
        $this->addSql('DROP TABLE IF EXISTS orders');
    }
}
