<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519009000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the Messaging admin read-model with integer IDs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS message_admin_message (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            message_uuid UUID NOT NULL,
            thread_id UUID NOT NULL,
            sender_user_id UUID NOT NULL,
            content TEXT NOT NULL,
            status VARCHAR(32) NOT NULL,
            position BIGINT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_message_admin_message_uuid ON message_admin_message (message_uuid)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_message_admin_message_thread_position ON message_admin_message (thread_id, position)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_message_admin_message_status ON message_admin_message (status)');

        $this->addSql('INSERT INTO message_admin_message (message_uuid, thread_id, sender_user_id, content, status, position, created_at, updated_at)
            SELECT id, thread_id, sender_user_id, content, status, position, created_at, updated_at
            FROM message_message
            ON CONFLICT (message_uuid) DO UPDATE SET
                thread_id = EXCLUDED.thread_id,
                sender_user_id = EXCLUDED.sender_user_id,
                content = EXCLUDED.content,
                status = EXCLUDED.status,
                position = EXCLUDED.position,
                created_at = EXCLUDED.created_at,
                updated_at = EXCLUDED.updated_at');

        $this->addSql(<<<'SQL'
CREATE OR REPLACE FUNCTION sync_message_admin_message() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM message_admin_message WHERE message_uuid = OLD.id;
        RETURN OLD;
    END IF;

    INSERT INTO message_admin_message (message_uuid, thread_id, sender_user_id, content, status, position, created_at, updated_at)
    VALUES (NEW.id, NEW.thread_id, NEW.sender_user_id, NEW.content, NEW.status, NEW.position, NEW.created_at, NEW.updated_at)
    ON CONFLICT (message_uuid) DO UPDATE SET
        thread_id = EXCLUDED.thread_id,
        sender_user_id = EXCLUDED.sender_user_id,
        content = EXCLUDED.content,
        status = EXCLUDED.status,
        position = EXCLUDED.position,
        created_at = EXCLUDED.created_at,
        updated_at = EXCLUDED.updated_at;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
SQL);
        $this->addSql('DROP TRIGGER IF EXISTS trg_sync_message_admin_message ON message_message');
        $this->addSql('CREATE TRIGGER trg_sync_message_admin_message AFTER INSERT OR UPDATE OR DELETE ON message_message FOR EACH ROW EXECUTE FUNCTION sync_message_admin_message()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TRIGGER IF EXISTS trg_sync_message_admin_message ON message_message');
        $this->addSql('DROP FUNCTION IF EXISTS sync_message_admin_message()');
        $this->addSql('DROP TABLE IF EXISTS message_admin_message');
    }
}
