<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519011100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore application_user table for Applicating admin list after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS application_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_identifier VARCHAR(120) NOT NULL, display_name VARCHAR(160) NOT NULL, email VARCHAR(180) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, auth_source VARCHAR(32) NOT NULL, external_subject VARCHAR(190) DEFAULT NULL, active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_application_user_identifier ON application_user (user_identifier)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_application_user_email ON application_user (email)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_application_user_external_subject ON application_user (external_subject)');

        foreach ([
            ['admin@smartresponsor.local', 'Admin Account', 'admin@smartresponsor.local', '["ROLE_ADMIN"]', 'local', null, true, '2026-05-19 00:00:00'],
            ['merchant@marketplace.test', 'Merchant Account', 'merchant@marketplace.test', '["ROLE_VENDOR"]', 'local', 'merchant-001', true, null],
            ['support@marketplace.test', 'Support Account', 'support@marketplace.test', '["ROLE_SUPPORT"]', 'local', 'support-001', true, null],
            ['buyer@marketplace.test', 'Buyer Account', 'buyer@marketplace.test', '["ROLE_CUSTOMER"]', 'local', 'buyer-001', true, null],
            ['ops@marketplace.test', 'Operations Account', 'ops@marketplace.test', '["ROLE_ADMIN","ROLE_SUPPORT"]', 'local', 'ops-001', true, null],
            ['sync@marketplace.test', 'Sync Bot', 'sync@marketplace.test', '["ROLE_SYSTEM"]', 'service', 'sync-bot-001', false, null],
        ] as [$identifier, $displayName, $email, $rolesJson, $authSource, $externalSubject, $active, $lastLoginAt]) {
            $this->addSql(
                'INSERT INTO application_user (user_identifier, display_name, email, roles, password, auth_source, external_subject, active, created_at, updated_at, last_login_at)
                 SELECT :user_identifier, :display_name, :email, :roles, NULL, :auth_source, :external_subject, ' . ($active ? 'true' : 'false') . ', NOW(), NOW(), :last_login_at
                 WHERE NOT EXISTS (
                     SELECT 1 FROM application_user WHERE user_identifier = :user_identifier
                 )',
                [
                    'user_identifier' => $identifier,
                    'display_name' => $displayName,
                    'email' => $email,
                    'roles' => $rolesJson,
                    'auth_source' => $authSource,
                    'external_subject' => $externalSubject,
                    'last_login_at' => $lastLoginAt,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS application_user');
    }
}
