<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260530120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create missing Taxating taxonomy tables for the generic CRUD surface.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, object_property_title VARCHAR(255) DEFAULT NULL, object_property_code VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, object_property_title VARCHAR(255) DEFAULT NULL, object_property_code VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, object_property_title VARCHAR(255) DEFAULT NULL, object_property_code VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(128) DEFAULT NULL, country VARCHAR(2) NOT NULL, county VARCHAR(64) DEFAULT NULL, postal_code_end VARCHAR(16) DEFAULT NULL, postal_code_start VARCHAR(16) DEFAULT NULL, priority SMALLINT NOT NULL DEFAULT 100, state VARCHAR(8) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(64) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, modified_by VARCHAR(64) DEFAULT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked_by VARCHAR(64) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_zone_country_state ON taxation_zone (country, state)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_zone_locality ON taxation_zone (country, state, county, city)');

        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value NUMERIC(9, 6) NOT NULL, version INT NOT NULL DEFAULT 1, category_id INT DEFAULT NULL, zone_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(64) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, modified_by VARCHAR(64) DEFAULT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked_by VARCHAR(64) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_rate_code ON taxation_rate (code)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_rate_cat_zone ON taxation_rate (category_id, zone_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_rate_validity ON taxation_rate (valid_from, valid_to)');

        $this->addSql('CREATE TABLE IF NOT EXISTS taxation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, currency VARCHAR(255) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, taxation_level_id INT DEFAULT NULL, taxation_type_id INT DEFAULT NULL, taxation_value_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_c8ee2a50c5b170bc ON taxation (taxation_level_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_c8ee2a507ac42112 ON taxation (taxation_type_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_c8ee2a50632080b9 ON taxation (taxation_value_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS taxation');
        $this->addSql('DROP TABLE IF EXISTS taxation_rate');
        $this->addSql('DROP TABLE IF EXISTS taxation_zone');
        $this->addSql('DROP TABLE IF EXISTS taxation_value');
        $this->addSql('DROP TABLE IF EXISTS taxation_type');
        $this->addSql('DROP TABLE IF EXISTS taxation_level');
    }
}
