<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519011300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore auxiliary Paying tables after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS payment_gateway (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, code VARCHAR(32) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_gateway_slug ON payment_gateway (slug)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_gateway_code ON payment_gateway (code)');

        $this->addSql('CREATE TABLE IF NOT EXISTS payment_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, code VARCHAR(32) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_method_slug ON payment_method (slug)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_method_code ON payment_method (code)');

        $this->addSql('CREATE TABLE IF NOT EXISTS payment_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, payment_id UUID NOT NULL, gateway_transaction_id VARCHAR(64) NOT NULL, type VARCHAR(16) NOT NULL, amount_minor INT NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_transaction_slug ON payment_transaction (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_payment_transaction_payment ON payment_transaction (payment_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS payment_refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, payment_id UUID NOT NULL, amount_minor INT NOT NULL, currency VARCHAR(3) NOT NULL, reason VARCHAR(64) DEFAULT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_refund_slug ON payment_refund (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_payment_refund_payment ON payment_refund (payment_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS payment_webhook_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, provider VARCHAR(32) NOT NULL, external_event_id VARCHAR(191) NOT NULL, payload JSON NOT NULL, status VARCHAR(16) NOT NULL DEFAULT \'received\', duplicate_count INT NOT NULL DEFAULT 0, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_webhook_slug ON payment_webhook_log (slug)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_webhook_provider_event ON payment_webhook_log (provider, external_event_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS payment_outbox_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, type VARCHAR(128) NOT NULL, payload JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) NOT NULL DEFAULT \'pending\', attempts INT NOT NULL DEFAULT 0, last_error TEXT DEFAULT NULL, routing_key VARCHAR(128) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_outbox_slug ON payment_outbox_message (slug)');

        $this->addSql('CREATE TABLE IF NOT EXISTS payment_dlq (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, outbox_id UUID NOT NULL, topic VARCHAR(128) NOT NULL, payload JSON NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');

        foreach ([
            ['2d1f5a7c-7b8a-4f1f-8b77-1d4b0a300001', 'stripe', 'STRIPE'],
            ['2d1f5a7c-7b8a-4f1f-8b77-1d4b0a300002', 'paypal', 'PAYPAL'],
            ['2d1f5a7c-7b8a-4f1f-8b77-1d4b0a300003', 'manual', 'MANUAL'],
            ['2d1f5a7c-7b8a-4f1f-8b77-1d4b0a300004', 'adyen', 'ADYEN'],
        ] as [$slug, $codeKey, $code]) {
            $this->addSql(
                'INSERT INTO payment_gateway (slug, code)
                 SELECT :slug, :code
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_gateway WHERE code = :code
                 )',
                ['slug' => $slug, 'code' => $code]
            );
            $this->addSql(
                'INSERT INTO payment_method (slug, code)
                 SELECT :slug, :code
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_method WHERE code = :code
                 )',
                ['slug' => $slug, 'code' => $codeKey]
            );
        }

        foreach ([
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5002', '22222222-2222-4222-8222-222222222201', 'gw_stripe_1002', 'capture', 4800],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5003', '22222222-2222-4222-8222-222222222202', 'gw_paypal_1003', 'capture', 19999],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5004', '22222222-2222-4222-8222-222222222203', 'gw_stripe_1004', 'authorization', 2500],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5005', '22222222-2222-4222-8222-222222222204', 'gw_internal_1005', 'refund', 7500],
        ] as [$paymentSlug, $slug, $gatewayTransactionId, $type, $amountMinor]) {
            $this->addSql(
                'INSERT INTO payment_transaction (slug, payment_id, gateway_transaction_id, type, amount_minor, occurred_at)
                 SELECT :slug, :payment_id, :gateway_transaction_id, :type, :amount_minor, NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_transaction WHERE slug = :slug
                 )',
                [
                    'slug' => $slug,
                    'payment_id' => $paymentSlug,
                    'gateway_transaction_id' => $gatewayTransactionId,
                    'type' => $type,
                    'amount_minor' => $amountMinor,
                ]
            );
        }

        foreach ([
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5005', '22222222-2222-4222-8222-222222222301', 7500, 'UAH', 'customer request'],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5004', '22222222-2222-4222-8222-222222222302', 2500, 'USD', 'fraud review reversal'],
        ] as [$paymentSlug, $slug, $amountMinor, $currency, $reason]) {
            $this->addSql(
                'INSERT INTO payment_refund (slug, payment_id, amount_minor, currency, reason, refunded_at)
                 SELECT :slug, :payment_id, :amount_minor, :currency, :reason, NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_refund WHERE slug = :slug
                 )',
                [
                    'slug' => $slug,
                    'payment_id' => $paymentSlug,
                    'amount_minor' => $amountMinor,
                    'currency' => $currency,
                    'reason' => $reason,
                ]
            );
        }

        foreach ([
            ['stripe', 'evt_stripe_1001', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5002","kind":"payment.captured"}', 'received', 0, null],
            ['paypal', 'evt_paypal_1002', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5003","kind":"payment.captured"}', 'processed', 0, '2026-05-19 00:00:00'],
            ['stripe', 'evt_stripe_1003', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5004","kind":"payment.failed"}', 'duplicate', 1, null],
            ['internal', 'evt_internal_1004', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5005","kind":"payment.refunded"}', 'processed', 0, '2026-05-19 00:00:00'],
        ] as [$provider, $externalEventId, $payload, $status, $duplicateCount, $processedAt]) {
            $this->addSql(
                'INSERT INTO payment_webhook_log (slug, provider, external_event_id, payload, status, duplicate_count, received_at, processed_at)
                 SELECT gen_random_uuid(), :provider, :external_event_id, :payload::json, :status, :duplicate_count, NOW(), :processed_at
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_webhook_log WHERE provider = :provider AND external_event_id = :external_event_id
                 )',
                [
                    'provider' => $provider,
                    'external_event_id' => $externalEventId,
                    'payload' => $payload,
                    'status' => $status,
                    'duplicate_count' => $duplicateCount,
                    'processed_at' => $processedAt,
                ]
            );
        }

        foreach ([
            ['3d1f5a7c-7b8a-4f1f-8b77-1d4b0a300101', 'payment.captured', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5002","status":"completed"}', 'payment.completed'],
            ['3d1f5a7c-7b8a-4f1f-8b77-1d4b0a300102', 'payment.failed', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5004","status":"failed"}', null],
            ['3d1f5a7c-7b8a-4f1f-8b77-1d4b0a300103', 'payment.refunded', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5005","status":"refunded"}', 'payment.refund.completed'],
        ] as [$slug, $type, $payload, $routingKey]) {
            $this->addSql(
                'INSERT INTO payment_outbox_message (slug, type, payload, occurred_at, status, attempts, last_error, routing_key)
                 SELECT :slug, :type, :payload::json, NOW(), \'pending\', 0, NULL, :routing_key
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_outbox_message WHERE slug = :slug
                 )',
                [
                    'slug' => $slug,
                    'type' => $type,
                    'payload' => $payload,
                    'routing_key' => $routingKey,
                ]
            );
        }

        foreach ([
            ['3d1f5a7c-7b8a-4f1f-8b77-1d4b0a300102', 'payment.failed', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5004","status":"failed"}', 'webhook retry budget exhausted'],
            ['3d1f5a7c-7b8a-4f1f-8b77-1d4b0a300103', 'payment.refunded', '{"paymentId":"8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5005","status":"refunded"}', 'manual review required'],
        ] as [$outboxId, $topic, $payload, $reason]) {
            $this->addSql(
                'INSERT INTO payment_dlq (outbox_id, topic, payload, reason, created_at)
                 SELECT :outbox_id, :topic, :payload::json, :reason, NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment_dlq WHERE outbox_id = :outbox_id AND topic = :topic
                 )',
                [
                    'outbox_id' => $outboxId,
                    'topic' => $topic,
                    'payload' => $payload,
                    'reason' => $reason,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS payment_dlq');
        $this->addSql('DROP TABLE IF EXISTS payment_outbox_message');
        $this->addSql('DROP TABLE IF EXISTS payment_webhook_log');
        $this->addSql('DROP TABLE IF EXISTS payment_refund');
        $this->addSql('DROP TABLE IF EXISTS payment_transaction');
        $this->addSql('DROP TABLE IF EXISTS payment_method');
        $this->addSql('DROP TABLE IF EXISTS payment_gateway');
    }
}
