<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Currencing currency table and seed a basic ISO storefront catalog after shared-db reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS currency_currency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(3) NOT NULL, numeric_code VARCHAR(3) DEFAULT NULL, minor_unit SMALLINT NOT NULL, symbol VARCHAR(16) DEFAULT NULL, display_name VARCHAR(128) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_currency_currency_code ON currency_currency (code)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_currency_currency_active_code ON currency_currency (active, code)');

        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'USD', '840', 2, '$', 'US Dollar', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'USD')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'EUR', '978', 2, '€', 'Euro', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'EUR')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'GBP', '826', 2, '£', 'British Pound', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'GBP')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'UAH', '980', 2, '₴', 'Ukrainian Hryvnia', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'UAH')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'PLN', '985', 2, 'zł', 'Polish Zloty', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'PLN')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'CZK', '203', 2, 'Kč', 'Czech Koruna', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'CZK')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'CHF', '756', 2, 'CHF', 'Swiss Franc', TRUE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'CHF')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO currency_currency (code, numeric_code, minor_unit, symbol, display_name, active)
SELECT 'JPY', '392', 0, '¥', 'Japanese Yen', FALSE
WHERE NOT EXISTS (SELECT 1 FROM currency_currency WHERE code = 'JPY')
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS currency_currency');
    }
}
