<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519011000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore subscription plan and subscription tables for Subscripting admin list after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS subscription_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(180) NOT NULL, description VARCHAR(500) DEFAULT NULL, period_count INT NOT NULL DEFAULT 1, period_unit VARCHAR(16) NOT NULL, trial_days INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT true, publicly_selectable BOOLEAN NOT NULL DEFAULT true, auto_renew_by_default BOOLEAN NOT NULL DEFAULT true, pricing_reference VARCHAR(120) DEFAULT NULL, currency_code VARCHAR(3) DEFAULT NULL, amount_minor_snapshot INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_subscription_plan_code ON subscription_plan (code)');
        $this->addSql('CREATE INDEX IF NOT EXISTS subscription_plan_active_idx ON subscription_plan (active)');

        $this->addSql('CREATE TABLE IF NOT EXISTS subscription_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_id INT NOT NULL, subject_type VARCHAR(80) NOT NULL, subject_id VARCHAR(120) NOT NULL, status VARCHAR(16) NOT NULL, auto_renew BOOLEAN NOT NULL, trial_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_period_starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_period_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancel_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paused_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, external_reference VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS subscription_subject_idx ON subscription_subscription (subject_type, subject_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS subscription_status_idx ON subscription_subscription (status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_subscription_plan_id ON subscription_subscription (plan_id)');
        $this->addSql('ALTER TABLE subscription_subscription ADD CONSTRAINT fk_subscription_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        foreach ([
            ['basic-monthly', 'Basic Monthly', 'Starter storefront subscription', 1, 'Month', 0, true, true, true, 'price_basic_monthly', 'USD', 990],
            ['pro-monthly', 'Pro Monthly', 'Merchant growth subscription', 1, 'Month', 7, true, true, true, 'price_pro_monthly', 'USD', 2990],
            ['pro-annual', 'Pro Annual', 'Annual storefront subscription', 12, 'Month', 14, true, true, true, 'price_pro_annual', 'EUR', 29900],
        ] as [$code, $name, $description, $periodCount, $periodUnit, $trialDays, $active, $publiclySelectable, $autoRenewByDefault, $pricingReference, $currencyCode, $amountMinorSnapshot]) {
            $this->addSql(
                'INSERT INTO subscription_plan (code, name, description, period_count, period_unit, trial_days, active, publicly_selectable, auto_renew_by_default, pricing_reference, currency_code, amount_minor_snapshot, created_at, updated_at)
                 SELECT :code, :name, :description, :period_count, :period_unit, :trial_days, ' . ($active ? 'true' : 'false') . ', ' . ($publiclySelectable ? 'true' : 'false') . ', ' . ($autoRenewByDefault ? 'true' : 'false') . ', :pricing_reference, :currency_code, :amount_minor_snapshot, NOW(), NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM subscription_plan WHERE code = :code
                 )',
                [
                    'code' => $code,
                    'name' => $name,
                    'description' => $description,
                    'period_count' => $periodCount,
                    'period_unit' => $periodUnit,
                    'trial_days' => $trialDays,
                    'pricing_reference' => $pricingReference,
                    'currency_code' => $currencyCode,
                    'amount_minor_snapshot' => $amountMinorSnapshot,
                ]
            );
        }

        foreach ([
            ['basic-monthly', 'merchant', 'store-001', 'draft', false, null, null, null, null, null, null, null, null, null, null],
            ['pro-monthly', 'merchant', 'store-002', 'trialing', true, '2026-06-19 00:00:00', null, null, null, null, null, null, null, null, null],
            ['pro-monthly', 'merchant', 'store-003', 'active', true, null, '2026-05-19 00:00:00', '2026-05-19 00:00:00', '2026-06-19 00:00:00', null, null, null, null, null, null],
            ['pro-annual', 'merchant', 'store-004', 'past_due', false, null, '2026-04-01 00:00:00', '2026-04-01 00:00:00', '2026-05-01 00:00:00', null, null, null, null, null, null],
            ['basic-monthly', 'vendor', 'vendor-001', 'paused', false, null, '2026-03-01 00:00:00', '2026-03-01 00:00:00', '2026-04-01 00:00:00', null, '2026-04-15 00:00:00', '2026-04-15 00:00:00', null, 'EXT-1001', null],
            ['pro-monthly', 'vendor', 'vendor-002', 'cancelled', false, null, '2026-02-01 00:00:00', '2026-02-01 00:00:00', '2026-03-01 00:00:00', '2026-04-20 00:00:00', '2026-04-20 00:00:00', null, null, 'EXT-1002', null],
        ] as [$planCode, $subjectType, $subjectId, $status, $autoRenew, $trialEndsAt, $activeFrom, $periodStartsAt, $periodEndsAt, $cancelAt, $cancelledAt, $pausedAt, $expiresAt, $externalReference, $reserved]) {
            $this->addSql(
                'INSERT INTO subscription_subscription (plan_id, subject_type, subject_id, status, auto_renew, trial_ends_at, active_from, current_period_starts_at, current_period_ends_at, cancel_at, cancelled_at, paused_at, expires_at, external_reference, created_at, updated_at)
                 SELECT p.id, :subject_type, :subject_id, :status, ' . ($autoRenew ? 'true' : 'false') . ', :trial_ends_at, :active_from, :current_period_starts_at, :current_period_ends_at, :cancel_at, :cancelled_at, :paused_at, :expires_at, :external_reference, NOW(), NOW()
                 FROM subscription_plan p
                 WHERE p.code = :plan_code
                   AND NOT EXISTS (
                       SELECT 1 FROM subscription_subscription s WHERE s.subject_id = :subject_id
                   )',
                [
                    'plan_code' => $planCode,
                    'subject_type' => $subjectType,
                    'subject_id' => $subjectId,
                    'status' => $status,
                    'trial_ends_at' => $trialEndsAt,
                    'active_from' => $activeFrom,
                    'current_period_starts_at' => $periodStartsAt,
                    'current_period_starts_at' => $periodStartsAt,
                    'current_period_ends_at' => $periodEndsAt,
                    'cancel_at' => $cancelAt,
                    'cancelled_at' => $cancelledAt,
                    'paused_at' => $pausedAt,
                    'expires_at' => $expiresAt,
                    'external_reference' => $externalReference,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS subscription_subscription');
        $this->addSql('DROP TABLE IF EXISTS subscription_plan');
    }
}
