<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519006000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Accessing authentication tables after accidental schema drop.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS accessing_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password_hash VARCHAR(255) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(32) DEFAULT NULL, totp_secret VARCHAR(255) DEFAULT NULL, email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, second_factor_enabled BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, failed_login_count INT NOT NULL, locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_sign_in_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_accessing_account_email ON accessing_account (email)');

        $this->addSql('CREATE TABLE IF NOT EXISTS credential (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, password_hash VARCHAR(255) NOT NULL, password_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_57f1d4b9b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS fk_57f1d4b9b6b5fba_idx ON credential (account_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS second_factor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, secret VARCHAR(128) NOT NULL, label VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_id INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_1806c29e9b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS fk_1806c29e9b6b5fba_idx ON second_factor (account_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS accessing_account_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_identifier VARCHAR(128) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, trusted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_id INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_1c28f99e9b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_1c28f99e97b88831 ON accessing_account_session (session_identifier)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_account_session_expires_at ON accessing_account_session (expires_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_account_session_revoked_at ON accessing_account_session (revoked_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_1c28f99e9b6b5fba ON accessing_account_session (account_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS accessing_recovery_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_hash VARCHAR(255) NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_f153bd6a9b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_f153bd6a9b6b5fba ON accessing_recovery_code (account_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_recovery_code_consumed_at ON accessing_recovery_code (consumed_at)');

        $this->addSql('CREATE TABLE IF NOT EXISTS accessing_reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_a57594089b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_a57594089b6b5fba ON accessing_reset_password_request (account_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS accessing_security_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(64) NOT NULL, context JSON NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT DEFAULT NULL, PRIMARY KEY (id), CONSTRAINT fk_907df8ca9b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_security_event_type ON accessing_security_event (event_type)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_907df8ca9b6b5fba ON accessing_security_event (account_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_security_event_occurred_at ON accessing_security_event (occurred_at)');

        $this->addSql('CREATE TABLE IF NOT EXISTS accessing_verification_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, channel_type VARCHAR(32) NOT NULL, token VARCHAR(255) NOT NULL, target VARCHAR(255) NOT NULL, completed BOOLEAN NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_86fad7139b6b5fba FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_verification_challenge_expires_at ON accessing_verification_challenge (expires_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_86fad7139b6b5fba ON accessing_verification_challenge (account_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_accessing_verification_challenge_type ON accessing_verification_challenge (channel_type)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS accessing_verification_challenge');
        $this->addSql('DROP TABLE IF EXISTS accessing_security_event');
        $this->addSql('DROP TABLE IF EXISTS accessing_reset_password_request');
        $this->addSql('DROP TABLE IF EXISTS accessing_recovery_code');
        $this->addSql('DROP TABLE IF EXISTS accessing_account_session');
        $this->addSql('DROP TABLE IF EXISTS second_factor');
        $this->addSql('DROP TABLE IF EXISTS credential');
        $this->addSql('DROP TABLE IF EXISTS accessing_account');
    }
}
