<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore payment table for Paying admin list after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, order_id VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL, amount NUMERIC(14, 2) NOT NULL, currency VARCHAR(3) NOT NULL, provider_ref VARCHAR(128) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_payment_slug ON payment (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_payment_order_id ON payment (order_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_payment_status ON payment (status)');

        foreach ([
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5001', 'ORD-10001', 'new', '12.50', 'USD', null],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5002', 'ORD-10002', 'processing', '48.00', 'USD', 'stripe_pi_1002'],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5003', 'ORD-10003', 'completed', '199.99', 'EUR', 'paypal_txn_1003'],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5004', 'ORD-10004', 'failed', '25.00', 'USD', 'stripe_fail_1004'],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5005', 'ORD-10005', 'refunded', '75.00', 'UAH', 'internal_refund_1005'],
            ['8a4f1c2e-9e33-4c1b-9a6f-1a2b3c4d5006', 'ORD-10006', 'pending', '10.00', 'USD', null],
        ] as [$slug, $orderId, $status, $amount, $currency, $providerRef]) {
            $this->addSql(
                'INSERT INTO payment (slug, order_id, status, amount, currency, provider_ref, created_at, updated_at)
                 SELECT :slug, :order_id, :status, :amount, :currency, :provider_ref, NOW(), NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM payment WHERE slug = :slug
                 )',
                [
                    'slug' => $slug,
                    'order_id' => $orderId,
                    'status' => $status,
                    'amount' => $amount,
                    'currency' => $currency,
                    'provider_ref' => $providerRef,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS payment');
    }
}
