<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519012400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore the attachment tables for Attaching after the shared schema drop.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\\Doctrine\\DBAL\\Platforms\\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE IF NOT EXISTS attachment (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            type VARCHAR(255) NOT NULL,
            media_kind VARCHAR(255) DEFAULT NULL,
            document_kind VARCHAR(255) DEFAULT NULL,
            storage_kind VARCHAR(255) NOT NULL,
            visibility VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL,
            original_name VARCHAR(255) NOT NULL,
            stored_name VARCHAR(255) NOT NULL,
            extension VARCHAR(32) DEFAULT NULL,
            mime_type VARCHAR(191) NOT NULL,
            size INT NOT NULL,
            checksum VARCHAR(128) NOT NULL,
            storage_path VARCHAR(1024) NOT NULL,
            title VARCHAR(255) DEFAULT NULL,
            description TEXT DEFAULT NULL,
            alt_text TEXT DEFAULT NULL,
            width INT DEFAULT NULL,
            height INT DEFAULT NULL,
            duration_ms INT DEFAULT NULL,
            page_count INT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_attachment_status ON attachment (status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_attachment_deleted_at ON attachment (deleted_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_attachment_storage_path ON attachment (storage_path)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_attachment_checksum_path ON attachment (checksum, storage_path)');

        $this->addSql('CREATE TABLE IF NOT EXISTS attachment_link (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            attachment_id INT NOT NULL,
            owner_type VARCHAR(191) NOT NULL,
            owner_id VARCHAR(191) NOT NULL,
            context VARCHAR(191) DEFAULT NULL,
            slot VARCHAR(191) DEFAULT NULL,
            "position" INT NOT NULL,
            is_primary BOOLEAN NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_attachment_link_attachment_id ON attachment_link (attachment_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_attachment_link_owner ON attachment_link (owner_type, owner_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_attachment_link_context_slot ON attachment_link (context, slot)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_attachment_link_owner_context_slot_position ON attachment_link (owner_type, owner_id, context, slot, "position")');
        $this->addSql('ALTER TABLE attachment_link ADD CONSTRAINT fk_attachment_link_attachment FOREIGN KEY (attachment_id) REFERENCES attachment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $now = 'NOW()';
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 1, 'document', NULL, 'text', 'local', 'private', 'active', 'sample-note.txt', 'message-note.txt', 'txt', 'text/plain', 44, 'e0f4d5af7d4bdfb1468d5c4f0bbd4f3b6cf1c8a8f3f8f4d7d2b2fb2b9d9f1a11', 'document/fixtures/message-note.txt', 'Message note', 'Fixture text attachment for message owner.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 1)
        ");
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 2, 'media', 'image', NULL, 'local', 'private', 'active', 'sample-pixel.gif', 'product-image.gif', 'gif', 'image/gif', 34, '9f2d6fef6e0b4da49f1d7f2c4f8d6b6d9a7e2c7d1f2b3a4c5d6e7f8a9b0c1d2e', 'media/fixtures/product-image.gif', 'Product image', 'Fixture image attachment for product owner.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 2)
        ");
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 3, 'media', 'image', NULL, 'local', 'private', 'active', 'sample-avatar.png', 'vendor-avatar.png', 'png', 'image/png', 0, '2b4e6d8f0a1c3e5f7b9d2c4a6e8f1b3d5f7a9c1e3b5d7f9a1c3e5f7b9d2c4a6', 'media/fixtures/vendor-avatar.png', 'Vendor avatar', 'Fixture avatar image attachment for vendor profile owner.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 3)
        ");
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 4, 'media', 'image', NULL, 'local', 'private', 'active', 'sample-product.png', 'product-banner.png', 'png', 'image/png', 0, '3c5e7f9a1b2d4f6e8a0c2d4f6e8a0c2d4f6e8a0c2d4f6e8a0c2d4f6e8a0c2d4f', 'media/fixtures/product-banner.png', 'Product banner', 'Fixture product banner image attachment.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 4)
        ");
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 5, 'media', 'image', NULL, 'local', 'private', 'active', 'sample-category.png', 'category-icon.png', 'png', 'image/png', 0, '4d6f8a0c2e4f6a8c0d2f4a6c8e0f2a4c6e8f0a2c4e6f8a0c2e4f6a8c0d2f4a6', 'media/fixtures/category-icon.png', 'Category icon', 'Fixture category icon image attachment.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 5)
        ");
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 6, 'media', 'image', NULL, 'local', 'private', 'active', 'sample-banner.png', 'vendor-banner.png', 'png', 'image/png', 0, '5e7f9a1c3d5e7f9a1c3d5e7f9a1c3d5e7f9a1c3d5e7f9a1c3d5e7f9a1c3d5e7f', 'media/fixtures/vendor-banner.png', 'Vendor banner', 'Fixture vendor banner image attachment.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 6)
        ");
        $this->addSql("
            INSERT INTO attachment (id, type, media_kind, document_kind, storage_kind, visibility, status, original_name, stored_name, extension, mime_type, size, checksum, storage_path, title, description, alt_text, width, height, duration_ms, page_count, created_at, updated_at, deleted_at)
            SELECT 7, 'document', NULL, 'pdf', 'local', 'private', 'active', 'vendor-policy.pdf', 'vendor-policy.pdf', 'pdf', 'application/pdf', 44, '6f8a0c2e4f6a8c0d2f4a6c8e0f2a4c6e8f0a2c4e6f8a0c2e4f6a8c0d2f4a6c8e', 'document/fixtures/vendor-policy.pdf', 'Vendor policy', 'Fixture pseudo-pdf attachment for vendor owner.', NULL, NULL, NULL, NULL, NULL, {$now}, {$now}, NULL
            WHERE NOT EXISTS (SELECT 1 FROM attachment WHERE id = 7)
        ");

        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 1, 1, 'message', 'msg-fixture-1', 'message', 'attachment', 0, true, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 1)
        ");
        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 2, 2, 'product', 'prod-fixture-1', 'gallery', 'image', 0, true, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 2)
        ");
        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 3, 3, 'vendor', 'vendor-fixture-1', 'profile', 'avatar', 0, true, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 3)
        ");
        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 4, 4, 'product', 'prod-fixture-1', 'gallery', 'banner', 1, false, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 4)
        ");
        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 5, 5, 'category', 'catalog-fixture-1', 'catalog', 'icon', 0, true, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 5)
        ");
        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 6, 6, 'vendor', 'vendor-fixture-1', 'profile', 'cover', 0, false, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 6)
        ");
        $this->addSql("
            INSERT INTO attachment_link (id, attachment_id, owner_type, owner_id, context, slot, \"position\", is_primary, created_at, updated_at)
            SELECT 7, 7, 'vendor', 'vendor-fixture-1', 'document', 'manual', 0, false, {$now}, {$now}
            WHERE NOT EXISTS (SELECT 1 FROM attachment_link WHERE id = 7)
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS attachment_link');
        $this->addSql('DROP TABLE IF EXISTS attachment');
    }
}
