<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519007000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore the orders table for Ordering after the shared schema drop.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS orders (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            slug UUID NOT NULL,
            number VARCHAR(64) NOT NULL,
            currency VARCHAR(3) NOT NULL,
            grand_total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
            paid_total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
            refunded_total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
            subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
            discount_total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
            tax_total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
            status VARCHAR(32) NOT NULL DEFAULT \'draft\',
            customer_id VARCHAR(64) DEFAULT NULL,
            vendor_id VARCHAR(64) DEFAULT NULL,
            tracking_code VARCHAR(64) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_orders_slug ON orders (slug)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_orders_number ON orders (number)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_orders_updated_at ON orders (updated_at)');

        $this->addSql("INSERT INTO orders (slug, number, currency, grand_total, paid_total, refunded_total, subtotal, discount_total, tax_total, status, customer_id, vendor_id, tracking_code, created_at, updated_at) VALUES
            ('6a9f1c5d-2b5b-4c8b-9c3e-1c1e0b1a0001', 'ORD-20260519-0001', 'USD', 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 'draft', 'customer-001', 'vendor-001', NULL, NOW(), NOW()),
            ('6a9f1c5d-2b5b-4c8b-9c3e-1c1e0b1a0002', 'ORD-20260519-0002', 'USD', 149.99, 149.99, 0.00, 149.99, 0.00, 0.00, 'paid', 'customer-002', 'vendor-001', NULL, NOW(), NOW()),
            ('6a9f1c5d-2b5b-4c8b-9c3e-1c1e0b1a0003', 'ORD-20260519-0003', 'EUR', 249.50, 249.50, 0.00, 249.50, 0.00, 0.00, 'shipped', 'customer-003', 'vendor-002', 'TRK-20260519-0003', NOW(), NOW())
            ON CONFLICT (number) DO NOTHING");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS orders');
    }
}
