<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore category table for Cataloging admin list after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(36) NOT NULL, parent_id VARCHAR(26) DEFAULT NULL, path LTREE NOT NULL, depth INT NOT NULL, locale VARCHAR(12) DEFAULT NULL, tenant VARCHAR(64) NOT NULL DEFAULT \'default\', workflow_state VARCHAR(32) NOT NULL DEFAULT \'draft\', published BOOLEAN NOT NULL DEFAULT false, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, icon_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_category_slug ON category (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_category_path ON category (path)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_category_tenant_workflow ON category (tenant, workflow_state)');

        foreach ([
            ['Marketplace', '126ac9f6-1490-481e-8b0e-97c2e939eaad', null, '126ac9f6-1490-481e-8b0e-97c2e939eaad', 0, 'default', 'published', true, '/fixtures/images/vendor-logo.svg'],
            ['Electronics', '126ac9f6-1490-481e-8b0e-97c2e939eaae', null, '126ac9f6-1490-481e-8b0e-97c2e939eaad.126ac9f6-1490-481e-8b0e-97c2e939eaae', 1, 'default', 'published', true, '/fixtures/images/product-card.svg'],
            ['Home & Kitchen', '126ac9f6-1490-481e-8b0e-97c2e939eaaf', null, '126ac9f6-1490-481e-8b0e-97c2e939eaad.126ac9f6-1490-481e-8b0e-97c2e939eaaf', 1, 'default', 'published', true, '/fixtures/images/category-icon.svg'],
            ['Beauty', '126ac9f6-1490-481e-8b0e-97c2e939eab0', null, '126ac9f6-1490-481e-8b0e-97c2e939eaad.126ac9f6-1490-481e-8b0e-97c2e939eab0', 1, 'default', 'draft', false, '/fixtures/images/avatar-user.svg'],
            ['Gift Cards', '126ac9f6-1490-481e-8b0e-97c2e939eab1', null, '126ac9f6-1490-481e-8b0e-97c2e939eaad.126ac9f6-1490-481e-8b0e-97c2e939eab1', 1, 'default', 'published', true, '/fixtures/images/avatar-admin.svg'],
            ['Outlet', '126ac9f6-1490-481e-8b0e-97c2e939eab2', null, '126ac9f6-1490-481e-8b0e-97c2e939eaad.126ac9f6-1490-481e-8b0e-97c2e939eab2', 1, 'default', 'draft', false, '/fixtures/images/product-card.svg'],
        ] as [$name, $slug, $parentId, $path, $depth, $tenant, $workflowState, $published, $iconUrl]) {
            $this->addSql(
                'INSERT INTO category (name, slug, parent_id, path, depth, locale, tenant, workflow_state, published, published_at, icon_url)
                 SELECT :name, :slug, :parent_id, :path, :depth, NULL, :tenant, :workflow_state, ' . ($published ? 'true' : 'false') . ', ' . ($published ? 'NOW()' : 'NULL') . ', :icon_url
                 WHERE NOT EXISTS (
                     SELECT 1 FROM category WHERE slug = :slug
                 )',
                [
                    'name' => $name,
                    'slug' => $slug,
                    'parent_id' => $parentId,
                    'path' => $path,
                    'depth' => $depth,
                    'tenant' => $tenant,
                    'workflow_state' => $workflowState,
                    'icon_url' => $iconUrl,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS category');
    }
}
