<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Exchanging exchange tables and demo currency rows after shared-db reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS exchange_exchange (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency_code VARCHAR(3) NOT NULL, quote_currency_code VARCHAR(3) NOT NULL, is_active BOOLEAN NOT NULL, created_at_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_exchange_pair ON exchange_exchange (base_currency_code, quote_currency_code)');
        $this->addSql('CREATE TABLE IF NOT EXISTS exchange_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency_code VARCHAR(3) NOT NULL, quote_currency_code VARCHAR(3) NOT NULL, rate_value NUMERIC(20, 10) NOT NULL, provider_code VARCHAR(80) NOT NULL, rate_date DATE NOT NULL, captured_at_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_exchange_rate_pair_date ON exchange_rate (base_currency_code, quote_currency_code, rate_date)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_exchange_rate_provider_date ON exchange_rate (provider_code, rate_date)');

        $this->addSql(<<<'SQL'
INSERT INTO exchange_exchange (base_currency_code, quote_currency_code, is_active, created_at_immutable)
SELECT 'USD', 'UAH', TRUE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_exchange WHERE base_currency_code = 'USD' AND quote_currency_code = 'UAH'
)
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO exchange_exchange (base_currency_code, quote_currency_code, is_active, created_at_immutable)
SELECT 'EUR', 'USD', TRUE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_exchange WHERE base_currency_code = 'EUR' AND quote_currency_code = 'USD'
)
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO exchange_exchange (base_currency_code, quote_currency_code, is_active, created_at_immutable)
SELECT 'USD', 'EUR', TRUE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_exchange WHERE base_currency_code = 'USD' AND quote_currency_code = 'EUR'
)
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO exchange_exchange (base_currency_code, quote_currency_code, is_active, created_at_immutable)
SELECT 'GBP', 'USD', TRUE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_exchange WHERE base_currency_code = 'GBP' AND quote_currency_code = 'USD'
)
SQL);

        $this->addSql(<<<'SQL'
INSERT INTO exchange_rate (base_currency_code, quote_currency_code, rate_value, provider_code, rate_date, captured_at_immutable)
SELECT 'USD', 'UAH', 41.2500000000, 'demo', CURRENT_DATE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_rate WHERE base_currency_code = 'USD' AND quote_currency_code = 'UAH' AND provider_code = 'demo' AND rate_date = CURRENT_DATE
)
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO exchange_rate (base_currency_code, quote_currency_code, rate_value, provider_code, rate_date, captured_at_immutable)
SELECT 'EUR', 'USD', 1.0800000000, 'demo', CURRENT_DATE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_rate WHERE base_currency_code = 'EUR' AND quote_currency_code = 'USD' AND provider_code = 'demo' AND rate_date = CURRENT_DATE
)
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO exchange_rate (base_currency_code, quote_currency_code, rate_value, provider_code, rate_date, captured_at_immutable)
SELECT 'USD', 'EUR', 0.9259000000, 'demo', CURRENT_DATE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_rate WHERE base_currency_code = 'USD' AND quote_currency_code = 'EUR' AND provider_code = 'demo' AND rate_date = CURRENT_DATE
)
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO exchange_rate (base_currency_code, quote_currency_code, rate_value, provider_code, rate_date, captured_at_immutable)
SELECT 'GBP', 'USD', 1.2500000000, 'demo', CURRENT_DATE, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_rate WHERE base_currency_code = 'GBP' AND quote_currency_code = 'USD' AND provider_code = 'demo' AND rate_date = CURRENT_DATE
)
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS exchange_rate');
        $this->addSql('DROP TABLE IF EXISTS exchange_exchange');
    }
}
