<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Localizing translation messages table and demo commerce copy after shared-db reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS locale_translation_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale_code VARCHAR(16) NOT NULL, domain_name VARCHAR(128) NOT NULL, key_name VARCHAR(255) NOT NULL, message TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_locale_translation_message ON locale_translation_message (locale_code, domain_name, key_name)');
        $this->addSql(<<<'SQL'
INSERT INTO locale_translation_message (locale_code, domain_name, key_name, message) VALUES
    ('en_US', 'storefront', 'hero_title', 'Shop premium essentials for every room'),
    ('en_GB', 'storefront', 'hero_title', 'Shop premium essentials for every room'),
    ('uk_UA', 'storefront', 'hero_title', 'Shop premium essentials for every room'),
    ('en_US', 'storefront', 'hero_subtitle', 'Fast delivery, easy returns, and trusted sellers.'),
    ('en_GB', 'storefront', 'hero_subtitle', 'Fast delivery, easy returns, and trusted sellers.'),
    ('uk_UA', 'storefront', 'hero_subtitle', 'Fast delivery, easy returns, and trusted sellers.'),
    ('en_US', 'storefront', 'featured_cta', 'Browse curated collections and seasonal offers.'),
    ('en_GB', 'storefront', 'featured_cta', 'Browse curated collections and seasonal offers.'),
    ('uk_UA', 'storefront', 'featured_cta', 'Browse curated collections and seasonal offers.'),
    ('en_US', 'checkout', 'cart_title', 'Your cart'),
    ('en_GB', 'checkout', 'cart_title', 'Your cart'),
    ('uk_UA', 'checkout', 'cart_title', 'Your cart'),
    ('en_US', 'checkout', 'checkout_button', 'Proceed to checkout'),
    ('en_GB', 'checkout', 'checkout_button', 'Proceed to checkout'),
    ('uk_UA', 'checkout', 'checkout_button', 'Proceed to checkout'),
    ('en_US', 'checkout', 'payment_hint', 'Secure payment and transparent shipping totals.'),
    ('en_GB', 'checkout', 'payment_hint', 'Secure payment and transparent shipping totals.'),
    ('uk_UA', 'checkout', 'payment_hint', 'Secure payment and transparent shipping totals.'),
    ('en_US', 'emails', 'order_subject', 'Your order has been confirmed'),
    ('en_GB', 'emails', 'order_subject', 'Your order has been confirmed'),
    ('uk_UA', 'emails', 'order_subject', 'Your order has been confirmed'),
    ('en_US', 'emails', 'shipment_subject', 'Your order is on the way'),
    ('en_GB', 'emails', 'shipment_subject', 'Your order is on the way'),
    ('uk_UA', 'emails', 'shipment_subject', 'Your order is on the way'),
    ('en_US', 'emails', 'support_subject', 'Customer support replied to your request.'),
    ('en_GB', 'emails', 'support_subject', 'Customer support replied to your request.'),
    ('uk_UA', 'emails', 'support_subject', 'Customer support replied to your request.')
ON CONFLICT (locale_code, domain_name, key_name) DO NOTHING
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DELETE FROM locale_translation_message WHERE (locale_code, domain_name, key_name) IN ((\'en_US\', \'storefront\', \'hero_title\'), (\'en_GB\', \'storefront\', \'hero_title\'), (\'uk_UA\', \'storefront\', \'hero_title\'), (\'en_US\', \'storefront\', \'hero_subtitle\'), (\'en_GB\', \'storefront\', \'hero_subtitle\'), (\'uk_UA\', \'storefront\', \'hero_subtitle\'), (\'en_US\', \'storefront\', \'featured_cta\'), (\'en_GB\', \'storefront\', \'featured_cta\'), (\'uk_UA\', \'storefront\', \'featured_cta\'), (\'en_US\', \'checkout\', \'cart_title\'), (\'en_GB\', \'checkout\', \'cart_title\'), (\'uk_UA\', \'checkout\', \'cart_title\'), (\'en_US\', \'checkout\', \'checkout_button\'), (\'en_GB\', \'checkout\', \'checkout_button\'), (\'uk_UA\', \'checkout\', \'checkout_button\'), (\'en_US\', \'checkout\', \'payment_hint\'), (\'en_GB\', \'checkout\', \'payment_hint\'), (\'uk_UA\', \'checkout\', \'payment_hint\'), (\'en_US\', \'emails\', \'order_subject\'), (\'en_GB\', \'emails\', \'order_subject\'), (\'uk_UA\', \'emails\', \'order_subject\'), (\'en_US\', \'emails\', \'shipment_subject\'), (\'en_GB\', \'emails\', \'shipment_subject\'), (\'uk_UA\', \'emails\', \'shipment_subject\'), (\'en_US\', \'emails\', \'support_subject\'), (\'en_GB\', \'emails\', \'support_subject\'), (\'uk_UA\', \'emails\', \'support_subject\'))');
    }
}
