<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore vendor table for Vendoring admin list after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS vendor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand_name VARCHAR(255) NOT NULL, owner_user_id INT DEFAULT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');

        foreach ([
            ['Market Vendor 01', 1001, 'active'],
            ['Market Vendor 02', 1002, 'active'],
            ['Market Vendor 03', 1003, 'inactive'],
            ['Market Vendor 04', 1004, 'active'],
            ['Market Vendor 05', 1005, 'active'],
            ['Market Vendor 06', 1006, 'inactive'],
        ] as [$brandName, $ownerUserId, $status]) {
            $this->addSql(
                'INSERT INTO vendor (brand_name, owner_user_id, status, created_at)
                 SELECT :brand_name, :owner_user_id, :status, NOW()
                 WHERE NOT EXISTS (
                     SELECT 1 FROM vendor WHERE brand_name = :brand_name
                 )',
                [
                    'brand_name' => $brandName,
                    'owner_user_id' => $ownerUserId,
                    'status' => $status,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS vendor');
    }
}
