<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Commissioning persistence tables and demo commission rows after shared-db reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS commission_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(180) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS commission_plan_code_unique ON commission_plan (code)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_beneficiary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, beneficiary_type VARCHAR(255) NOT NULL, beneficiary_reference VARCHAR(120) NOT NULL, display_name VARCHAR(180) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS commission_beneficiary_reference_unique ON commission_beneficiary (beneficiary_type, beneficiary_reference)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_id INT NOT NULL, type VARCHAR(255) NOT NULL, percentage_rate VARCHAR(32) DEFAULT NULL, fixed_minor_amount INT DEFAULT NULL, currency_code VARCHAR(3) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS commission_rate_type_idx ON commission_rate (type)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_id INT NOT NULL, rule_key VARCHAR(120) NOT NULL, operator VARCHAR(255) NOT NULL, expected_value VARCHAR(255) DEFAULT NULL, priority INT NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS commission_rule_key_idx ON commission_rule (rule_key)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_tier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rate_id INT NOT NULL, minimum_minor_amount INT NOT NULL, maximum_minor_amount INT DEFAULT NULL, percentage_rate VARCHAR(32) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS commission_tier_minimum_idx ON commission_tier (minimum_minor_amount)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_calculation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_id INT NOT NULL, economic_event_reference VARCHAR(120) NOT NULL, currency_code VARCHAR(3) NOT NULL, basis_minor_amount INT NOT NULL, commission_minor_amount INT NOT NULL, status VARCHAR(255) NOT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS commission_calculation_event_idx ON commission_calculation (economic_event_reference)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_calculation_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calculation_id INT NOT NULL, line_type VARCHAR(255) NOT NULL, currency_code VARCHAR(3) NOT NULL, minor_amount INT NOT NULL, explanation VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_ledger_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calculation_id INT NOT NULL, beneficiary_reference VARCHAR(120) NOT NULL, currency_code VARCHAR(3) NOT NULL, minor_amount INT NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS commission_ledger_beneficiary_idx ON commission_ledger_entry (beneficiary_reference)');
        $this->addSql('CREATE INDEX IF NOT EXISTS commission_ledger_status_idx ON commission_ledger_entry (status)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_settlement_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, batch_reference VARCHAR(120) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS commission_settlement_batch_reference_unique ON commission_settlement_batch (batch_reference)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_settlement_batch_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, batch_id INT NOT NULL, ledger_entry_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS commission_settlement_batch_entry_unique ON commission_settlement_batch_entry (batch_id, ledger_entry_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_attribution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_type VARCHAR(255) NOT NULL, source_reference VARCHAR(120) NOT NULL, economic_event_reference VARCHAR(120) NOT NULL, PRIMARY KEY(id))');

        $this->addSql('CREATE TABLE IF NOT EXISTS commission_tier_seed_marker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note VARCHAR(120) NOT NULL, PRIMARY KEY(id))');

        $this->addSql(<<<'SQL'
INSERT INTO commission_plan (code, name, active, created_at)
SELECT 'plan-01', 'Marketplace Commission Plan', TRUE, NOW()
WHERE NOT EXISTS (SELECT 1 FROM commission_plan WHERE code = 'plan-01')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_plan (code, name, active, created_at)
SELECT 'plan-02', 'Affiliate Commission Plan', TRUE, NOW()
WHERE NOT EXISTS (SELECT 1 FROM commission_plan WHERE code = 'plan-02')
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_plan (code, name, active, created_at)
SELECT 'plan-03', 'Partner Commission Plan', TRUE, NOW()
WHERE NOT EXISTS (SELECT 1 FROM commission_plan WHERE code = 'plan-03')
SQL);

        $this->addSql(<<<'SQL'
INSERT INTO commission_beneficiary (beneficiary_type, beneficiary_reference, display_name, active)
VALUES
    ('partner', 'partner-01', 'SmartPartner Commerce LLC', TRUE),
    ('affiliate', 'affiliate-01', 'Affiliate North', TRUE),
    ('partner', 'partner-02', 'Vendor Growth Studio', TRUE),
    ('affiliate', 'affiliate-02', 'Creator Boost Network', TRUE),
    ('reseller', 'reseller-01', 'Reseller Hub', TRUE),
    ('marketplace_seller', 'seller-01', 'Marketplace Seller One', TRUE)
ON CONFLICT (beneficiary_type, beneficiary_reference) DO NOTHING
SQL);

        $this->addSql(<<<'SQL'
INSERT INTO commission_rate (plan_id, type, percentage_rate, fixed_minor_amount, currency_code, active)
SELECT p.id, 'percentage', '0.1200', NULL, NULL, TRUE FROM commission_plan p WHERE p.code = 'plan-01'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_rate (plan_id, type, percentage_rate, fixed_minor_amount, currency_code, active)
SELECT p.id, 'fixed', NULL, 750, 'USD', TRUE FROM commission_plan p WHERE p.code = 'plan-01'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_rate (plan_id, type, percentage_rate, fixed_minor_amount, currency_code, active)
SELECT p.id, 'hybrid', '0.0750', 500, 'USD', TRUE FROM commission_plan p WHERE p.code = 'plan-02'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_rate (plan_id, type, percentage_rate, fixed_minor_amount, currency_code, active)
SELECT p.id, 'tiered', NULL, NULL, NULL, TRUE FROM commission_plan p WHERE p.code = 'plan-03'
ON CONFLICT DO NOTHING
SQL);

        $this->addSql(<<<'SQL'
INSERT INTO commission_rule (plan_id, rule_key, operator, expected_value, priority, active)
SELECT p.id, 'order.currency', 'in', 'USD,EUR,UAH', 100, TRUE FROM commission_plan p WHERE p.code = 'plan-01'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_rule (plan_id, rule_key, operator, expected_value, priority, active)
SELECT p.id, 'order.amount_minor', 'greater_than_or_equal', '1000', 90, TRUE FROM commission_plan p WHERE p.code = 'plan-02'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_rule (plan_id, rule_key, operator, expected_value, priority, active)
SELECT p.id, 'seller.status', 'equals', 'active', 80, TRUE FROM commission_plan p WHERE p.code = 'plan-03'
ON CONFLICT DO NOTHING
SQL);

        $this->addSql(<<<'SQL'
INSERT INTO commission_tier (rate_id, minimum_minor_amount, maximum_minor_amount, percentage_rate)
SELECT r.id, 0, 9999, '0.0800'
FROM commission_rate r
JOIN commission_plan p ON p.id = r.plan_id
WHERE p.code = 'plan-03' AND r.type = 'tiered'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_tier (rate_id, minimum_minor_amount, maximum_minor_amount, percentage_rate)
SELECT r.id, 10000, 49999, '0.1000'
FROM commission_rate r
JOIN commission_plan p ON p.id = r.plan_id
WHERE p.code = 'plan-03' AND r.type = 'tiered'
ON CONFLICT DO NOTHING
SQL);
        $this->addSql(<<<'SQL'
INSERT INTO commission_tier (rate_id, minimum_minor_amount, maximum_minor_amount, percentage_rate)
SELECT r.id, 50000, NULL, '0.1200'
FROM commission_rate r
JOIN commission_plan p ON p.id = r.plan_id
WHERE p.code = 'plan-03' AND r.type = 'tiered'
ON CONFLICT DO NOTHING
SQL);

        for ($index = 1; $index <= 3; ++$index) {
            $planCode = sprintf('plan-%02d', $index);
            $tenantId = sprintf('merchant_%02d', $index);
            $eventRef = sprintf('event-EVT-%05d-%02d', 40000 + $index, $index);
            $batchRef = sprintf('batch-%02d', $index);
            $currency = ['USD', 'EUR', 'UAH'][($index - 1) % 3];
            $basis = 10000 + ($index * 3500);
            $commission = 1200 + ($index * 275);
            $status = 'calculated';
            $ledgerStatus = 'pending';
            $beneficiaryRef = match ($index) {
                1 => 'partner-01',
                2 => 'affiliate-01',
                default => 'partner-02',
            };

            $this->addSql(<<<SQL
INSERT INTO commission_calculation (plan_id, economic_event_reference, currency_code, basis_minor_amount, commission_minor_amount, status, calculated_at)
SELECT p.id, '{$eventRef}', '{$currency}', {$basis}, {$commission}, '{$status}', NOW()
FROM commission_plan p WHERE p.code = '{$planCode}'
ON CONFLICT DO NOTHING
SQL);

            $this->addSql(<<<SQL
INSERT INTO commission_calculation_line (calculation_id, line_type, currency_code, minor_amount, explanation)
SELECT c.id, 'base', '{$currency}', {$basis}, 'Basis amount'
FROM commission_calculation c WHERE c.economic_event_reference = '{$eventRef}'
ON CONFLICT DO NOTHING
SQL);
            $this->addSql(<<<SQL
INSERT INTO commission_calculation_line (calculation_id, line_type, currency_code, minor_amount, explanation)
SELECT c.id, 'percentage_commission', '{$currency}', {$commission}, 'Percentage commission'
FROM commission_calculation c WHERE c.economic_event_reference = '{$eventRef}'
ON CONFLICT DO NOTHING
SQL);

            $this->addSql(<<<SQL
INSERT INTO commission_ledger_entry (calculation_id, beneficiary_reference, currency_code, minor_amount, status)
SELECT c.id, '{$beneficiaryRef}', '{$currency}', {$commission}, '{$ledgerStatus}'
FROM commission_calculation c WHERE c.economic_event_reference = '{$eventRef}'
ON CONFLICT DO NOTHING
SQL);

            $this->addSql(<<<SQL
INSERT INTO commission_settlement_batch (batch_reference, status, created_at)
SELECT '{$batchRef}', 'draft', NOW()
WHERE NOT EXISTS (SELECT 1 FROM commission_settlement_batch WHERE batch_reference = '{$batchRef}')
SQL);

            $this->addSql(<<<SQL
INSERT INTO commission_settlement_batch_entry (batch_id, ledger_entry_id)
SELECT b.id, l.id
FROM commission_settlement_batch b
JOIN commission_ledger_entry l ON l.beneficiary_reference = '{$beneficiaryRef}' AND l.currency_code = '{$currency}' AND l.minor_amount = {$commission}
WHERE b.batch_reference = '{$batchRef}'
ON CONFLICT DO NOTHING
SQL);

            $this->addSql(<<<SQL
INSERT INTO commission_attribution (source_type, source_reference, economic_event_reference)
SELECT 'affiliate', '{$tenantId}', '{$eventRef}'
WHERE NOT EXISTS (SELECT 1 FROM commission_attribution WHERE source_reference = '{$tenantId}' AND economic_event_reference = '{$eventRef}')
SQL);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS commission_attribution');
        $this->addSql('DROP TABLE IF EXISTS commission_settlement_batch_entry');
        $this->addSql('DROP TABLE IF EXISTS commission_settlement_batch');
        $this->addSql('DROP TABLE IF EXISTS commission_ledger_entry');
        $this->addSql('DROP TABLE IF EXISTS commission_calculation_line');
        $this->addSql('DROP TABLE IF EXISTS commission_calculation');
        $this->addSql('DROP TABLE IF EXISTS commission_tier');
        $this->addSql('DROP TABLE IF EXISTS commission_rule');
        $this->addSql('DROP TABLE IF EXISTS commission_rate');
        $this->addSql('DROP TABLE IF EXISTS commission_beneficiary');
        $this->addSql('DROP TABLE IF EXISTS commission_plan');
        $this->addSql('DROP TABLE IF EXISTS commission_tier_seed_marker');
    }
}
