<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Billing persistence tables and demo tenant rows after shared-db reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS billing_rate_limits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(255) NOT NULL, actor_tenant_id VARCHAR(255) NOT NULL, operation_name VARCHAR(255) NOT NULL, bucket_started_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, counter INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_billing_rate_limit_bucket ON billing_rate_limits (tenant_id, actor_tenant_id, operation_name, bucket_started_at)');

        $this->addSql('CREATE TABLE IF NOT EXISTS billing_ledger (tenant_id VARCHAR(255) NOT NULL, entry_id VARCHAR(255) NOT NULL, reference VARCHAR(255) DEFAULT NULL, amount INT DEFAULT NULL, currency VARCHAR(255) DEFAULT NULL, customer VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(tenant_id, entry_id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_billing_ledger_tenant_reference ON billing_ledger (tenant_id, reference)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_billing_ledger_tenant_customer ON billing_ledger (tenant_id, customer)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_billing_ledger_tenant_type ON billing_ledger (tenant_id, type)');

        $this->addSql('CREATE TABLE IF NOT EXISTS billing_invoices (tenant_id VARCHAR(255) NOT NULL, invoice_number VARCHAR(255) NOT NULL, customer VARCHAR(255) DEFAULT NULL, amount INT DEFAULT NULL, currency VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, ledger_entry_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, finalized_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(tenant_id, invoice_number))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_billing_invoices_tenant_status ON billing_invoices (tenant_id, status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_billing_invoices_tenant_customer ON billing_invoices (tenant_id, customer)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_billing_invoices_tenant_ledger_entry ON billing_invoices (tenant_id, ledger_entry_id)');

        $this->addSql('CREATE TABLE IF NOT EXISTS billing_idempotency (tenant_id VARCHAR(255) NOT NULL, action_name VARCHAR(255) NOT NULL, idempotency_key VARCHAR(255) NOT NULL, response_json TEXT NOT NULL, PRIMARY KEY(tenant_id, action_name, idempotency_key))');

        for ($index = 1; $index <= 6; ++$index) {
            $tenantId = sprintf('merchant_%02d', $index);
            $invoiceNumber = sprintf('INV-2025-%05d', 10000 + $index);
            $entryId = sprintf('ledger-%05d', 20000 + $index);
            $currency = ['USD', 'EUR', 'UAH'][($index - 1) % 3];
            $amount = 1499 + ($index * 325);
            $counter = 5 + $index;
            $status = match ($index % 3) {
                0 => 'finalized',
                1 => 'draft',
                default => 'issued',
            };

            $this->addSql(<<<SQL
INSERT INTO billing_ledger (tenant_id, entry_id, reference, amount, currency, customer, type, created_at)
SELECT '{$tenantId}', '{$entryId}', 'order:{$invoiceNumber}', {$amount}, '{$currency}', 'customer_' || LPAD('' || (7000 + {$index}), 4, '0'), CASE WHEN MOD({$index}, 2) = 0 THEN 'credit' ELSE 'debit' END, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM billing_ledger WHERE tenant_id = '{$tenantId}' AND entry_id = '{$entryId}'
)
SQL);

            $this->addSql(<<<SQL
INSERT INTO billing_invoices (tenant_id, invoice_number, customer, amount, currency, status, ledger_entry_id, created_at, updated_at, finalized_at)
SELECT '{$tenantId}', '{$invoiceNumber}', 'customer_' || LPAD('' || (7000 + {$index}), 4, '0'), {$amount}, '{$currency}', '{$status}', '{$entryId}', NOW(), NOW(), CASE WHEN '{$status}' = 'finalized' THEN NOW() ELSE NULL END
WHERE NOT EXISTS (
    SELECT 1 FROM billing_invoices WHERE tenant_id = '{$tenantId}' AND invoice_number = '{$invoiceNumber}'
)
SQL);

            $bucketStartedAt = (new \DateTimeImmutable(sprintf('-%d hour', $index)))->format('Y-m-d H:i:sP');
            $this->addSql(<<<SQL
INSERT INTO billing_rate_limits (tenant_id, actor_tenant_id, operation_name, bucket_started_at, counter)
SELECT '{$tenantId}', '{$tenantId}', 'billing.invoice.create', '{$bucketStartedAt}', {$counter}
WHERE NOT EXISTS (
    SELECT 1 FROM billing_rate_limits WHERE tenant_id = '{$tenantId}' AND actor_tenant_id = '{$tenantId}' AND operation_name = 'billing.invoice.create' AND bucket_started_at = '{$bucketStartedAt}'
)
SQL);

            $responseJson = json_encode([
                'invoice' => $invoiceNumber,
                'entry_id' => $entryId,
                'status' => $status,
                'customer' => sprintf('customer_%04d', 7000 + $index),
            ], JSON_THROW_ON_ERROR);
            $responseJson = str_replace("'", "''", $responseJson);

            $this->addSql(<<<SQL
INSERT INTO billing_idempotency (tenant_id, action_name, idempotency_key, response_json)
SELECT '{$tenantId}', 'billing.invoice.create', 'idem-{$invoiceNumber}', '{$responseJson}'
WHERE NOT EXISTS (
    SELECT 1 FROM billing_idempotency WHERE tenant_id = '{$tenantId}' AND action_name = 'billing.invoice.create' AND idempotency_key = 'idem-{$invoiceNumber}'
)
SQL);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS billing_idempotency');
        $this->addSql('DROP TABLE IF EXISTS billing_invoices');
        $this->addSql('DROP TABLE IF EXISTS billing_ledger');
        $this->addSql('DROP TABLE IF EXISTS billing_rate_limits');
    }
}
