<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260429194000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add vendoring vendor_category table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE vendor_category (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vendor_id INT NOT NULL,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(255) DEFAULT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_vendor_category_vendor_category ON vendor_category (vendor_id, category_code)');
        $this->addSql('CREATE INDEX idx_vendor_category_vendor_primary ON vendor_category (vendor_id, is_primary)');
        $this->addSql('ALTER TABLE vendor_category ADD CONSTRAINT fk_vendor_category_vendor FOREIGN KEY (vendor_id) REFERENCES vendor (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE vendor_category');
    }
}
