<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519010700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Restore Taxating product, category, and product-category tables after shared DB reset.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_product_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, digital BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_taxation_product_sku ON taxation_product_entity (sku)');

        $this->addSql('CREATE TABLE IF NOT EXISTS taxation_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(64) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_taxation_category_code ON taxation_category (code)');

        $this->addSql('CREATE TABLE IF NOT EXISTS product_tax_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_product_taxcat ON product_tax_category (product_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_product_taxcat_category ON product_tax_category (category_id)');
        $this->addSql('ALTER TABLE product_tax_category ADD CONSTRAINT fk_product_taxcat_category FOREIGN KEY (category_id) REFERENCES taxation_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        foreach ([
            ['BOOK', 'Books & Education'],
            ['DIGITAL', 'Digital Services'],
            ['FOOD', 'Food & Grocery'],
            ['CLOTHES', 'Apparel & Accessories'],
            ['MEDICAL', 'Health & Wellness'],
        ] as [$code, $name]) {
            $this->addSql(
                'INSERT INTO taxation_category (code, name, created_at, created_by, updated_at)
                 SELECT :code, :name, NOW(), :created_by, NULL
                 WHERE NOT EXISTS (
                     SELECT 1 FROM taxation_category WHERE code = :code
                 )',
                [
                    'code' => $code,
                    'name' => $name,
                    'created_by' => 'fixture',
                ]
            );
        }

        foreach ([
            ['BOOK-PLAYBOOK-001', 'Marketplace Playbook', 'Commerce growth handbook for sellers and operators.', false, 'BOOK'],
            ['DIGITAL-BUNDLE-014', 'Checkout Email Template Pack', 'Ready-to-use email copy for abandoned carts and order confirmation.', true, 'DIGITAL'],
            ['FOOD-COFFEE-008', 'Single-Origin Coffee Beans', 'Fresh roasted coffee for subscription and one-time orders.', false, 'FOOD'],
            ['CLOTHES-HOODIE-021', 'Relaxed Fit Hoodie', 'Unisex apparel in core marketplace sizes and colors.', false, 'CLOTHES'],
            ['MEDICAL-THERMO-004', 'Digital Wellness Thermometer', 'Health and wellness accessory with calibration certificate.', false, 'MEDICAL'],
            ['DIGITAL-GIFT-099', 'Gift Card Credit', 'Digital store credit for gifts, returns, and retention campaigns.', true, 'DIGITAL'],
        ] as [$sku, $name, $description, $digital, $categoryCode]) {
            $this->addSql(
                'INSERT INTO taxation_product_entity (sku, name, description, digital)
                 SELECT :sku, :name, :description, ' . ($digital ? 'true' : 'false') . '
                 WHERE NOT EXISTS (
                     SELECT 1 FROM taxation_product_entity WHERE sku = :sku
                 )',
                [
                    'sku' => $sku,
                    'name' => $name,
                    'description' => $description,
                ]
            );

            $this->addSql(
                'INSERT INTO product_tax_category (category_id, product_id)
                 SELECT c.id, p.id
                 FROM taxation_category c
                 INNER JOIN taxation_product_entity p ON p.sku = :sku
                 WHERE c.code = :category_code
                   AND NOT EXISTS (
                       SELECT 1 FROM product_tax_category ptc WHERE ptc.product_id = p.id
                   )',
                [
                    'sku' => $sku,
                    'category_code' => $categoryCode,
                ]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS product_tax_category');
        $this->addSql('DROP TABLE IF EXISTS taxation_category');
        $this->addSql('DROP TABLE IF EXISTS taxation_product_entity');
    }
}
