<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519011700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recover Tagging tag and admin projection tables for EasyAdmin.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE IF NOT EXISTS tag (
    id VARCHAR(26) NOT NULL,
    tenant VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    label VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    required_flag BOOLEAN NOT NULL,
    mod_only_flag BOOLEAN NOT NULL,
    PRIMARY KEY(id, tenant)
)
SQL);

        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS tag_slug_uq ON tag (tenant, slug)');

        $this->addSql('DROP TABLE IF EXISTS tag_admin_view');
        $this->addSql(<<<'SQL'
CREATE TABLE tag_admin_view (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_id VARCHAR(26) NOT NULL,
    tenant VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    label VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    required_flag BOOLEAN NOT NULL,
    mod_only_flag BOOLEAN NOT NULL,
    PRIMARY KEY(id)
)
SQL);

        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS tag_admin_view_tag_uq ON tag_admin_view (tenant, tag_id)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS tag_admin_view_slug_uq ON tag_admin_view (tenant, slug)');

        $this->addSql(<<<'SQL'
INSERT INTO tag (id, tenant, slug, label, created_at, updated_at, required_flag, mod_only_flag)
VALUES
    ('tag-00000001', 'tenant-a', 'summer-sale', 'Summer sale', '2026-05-19 08:00:00', NULL, false, false),
    ('tag-00000002', 'tenant-a', 'free-shipping', 'Free shipping', '2026-05-19 08:00:00', NULL, true, false),
    ('tag-00000003', 'tenant-a', 'best-sellers', 'Best sellers', '2026-05-19 08:00:00', NULL, false, false),
    ('tag-00000004', 'tenant-b', 'clearance', 'Clearance', '2026-05-19 08:00:00', NULL, false, true),
    ('tag-00000005', 'tenant-b', 'gift-ideas', 'Gift ideas', '2026-05-19 08:00:00', NULL, false, false)
ON CONFLICT (id, tenant) DO UPDATE SET
    slug = EXCLUDED.slug,
    label = EXCLUDED.label,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    required_flag = EXCLUDED.required_flag,
    mod_only_flag = EXCLUDED.mod_only_flag
SQL);

        $this->addSql(<<<'SQL'
INSERT INTO tag_admin_view (tag_id, tenant, slug, label, created_at, updated_at, required_flag, mod_only_flag)
SELECT
    id AS tag_id,
    tenant,
    slug,
    label,
    created_at,
    updated_at,
    required_flag,
    mod_only_flag
FROM tag
ORDER BY tenant, id
ON CONFLICT (tenant, tag_id) DO UPDATE SET
    slug = EXCLUDED.slug,
    label = EXCLUDED.label,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    required_flag = EXCLUDED.required_flag,
    mod_only_flag = EXCLUDED.mod_only_flag
SQL);

        $this->addSql(<<<'SQL'
CREATE OR REPLACE FUNCTION sync_tag_admin_view() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM tag_admin_view
        WHERE tenant = OLD.tenant
          AND tag_id = OLD.id;
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        UPDATE tag_admin_view
        SET tenant = NEW.tenant,
            slug = NEW.slug,
            label = NEW.label,
            created_at = NEW.created_at,
            updated_at = NEW.updated_at,
            required_flag = NEW.required_flag,
            mod_only_flag = NEW.mod_only_flag
        WHERE tenant = OLD.tenant
          AND tag_id = OLD.id;
        RETURN NEW;
    ELSE
        INSERT INTO tag_admin_view (tag_id, tenant, slug, label, created_at, updated_at, required_flag, mod_only_flag)
        VALUES (NEW.id, NEW.tenant, NEW.slug, NEW.label, NEW.created_at, NEW.updated_at, NEW.required_flag, NEW.mod_only_flag)
        ON CONFLICT (tenant, tag_id) DO UPDATE SET
            slug = EXCLUDED.slug,
            label = EXCLUDED.label,
            created_at = EXCLUDED.created_at,
            updated_at = EXCLUDED.updated_at,
            required_flag = EXCLUDED.required_flag,
            mod_only_flag = EXCLUDED.mod_only_flag;
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;
SQL);

        $this->addSql('DROP TRIGGER IF EXISTS trg_sync_tag_admin_view ON tag');
        $this->addSql('CREATE TRIGGER trg_sync_tag_admin_view AFTER INSERT OR UPDATE OR DELETE ON tag FOR EACH ROW EXECUTE FUNCTION sync_tag_admin_view()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TRIGGER IF EXISTS trg_sync_tag_admin_view ON tag');
        $this->addSql('DROP FUNCTION IF EXISTS sync_tag_admin_view()');
        $this->addSql('DROP TABLE IF EXISTS tag_admin_view');
        $this->addSql('DROP TABLE IF EXISTS tag');
    }
}
