<?php

declare(strict_types=1);

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MercureBundle\MercureBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Scheb\TwoFactorBundle\SchebTwoFactorBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    App\Cruding\CrudingBundle::class => ['all' => true],
    App\Messaging\MessagingBundle::class => ['all' => true],
    App\Analysing\AnalysingBundle::class => ['all' => true],
    App\Attaching\AttachingBundle::class => ['all' => true],
    App\Billing\BillingBundle::class => ['all' => true],
    App\Commissioning\CommissioningBundle::class => ['all' => true],
    App\Exchanging\ExchangingBundle::class => ['all' => true],
    App\Rolling\RollingBundle::class => ['all' => true],
    App\Taxating\TaxatingBundle::class => ['all' => true],
    App\Tagging\TaggingBundle::class => ['all' => true],
    App\Interfacing\InterfacingBundle::class => ['all' => true],
    App\Paging\PageBundle::class => ['all' => true],
    App\Managing\ManagingBundle::class => ['all' => true],
    App\Accessing\AccessingBundle::class => ['all' => true],
    App\Bridging\BridgingBundle::class => ['all' => true],
    App\Cataloging\CatalogingBundle::class => ['all' => true],
    App\Indexing\IndexingBundle::class => ['all' => true],
    App\Vendoring\VendoringBundle::class => ['all' => true],
    App\Applicating\ApplicatingBundle::class => ['all' => true],
    App\Subscripting\Bundle\SubscriptionBundle::class => ['all' => true],
];
