<?php

declare(strict_types=1);

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
    Symfony\UX\Turbo\TurboBundle::class => ['all' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    App\Accessing\AccessingBundle::class => ['all' => true],
    App\Administering\AdministeringBundle::class => ['all' => true],
    App\Applicating\ApplicatingBundle::class => ['all' => true],
    App\Carting\CartingBundle::class => ['all' => true],
    App\Cataloging\CatalogingBundle::class => ['all' => true],
    App\Cruding\CrudingBundle::class => ['all' => true],
    App\Interfacing\InterfacingBundle::class => ['all' => true],
    App\Localizing\LocalizingBundle::class => ['all' => true],
    App\Managing\ManagingBundle::class => ['all' => true],
    App\Navigating\NavigatingBundle::class => ['all' => true],
    App\Objecting\ObjectBundle::class => ['all' => true],
    App\Paging\PageBundle::class => ['all' => true],
    App\Rolling\RollingBundle::class => ['all' => true],
    App\Searching\SearchingBundle::class => ['all' => true],
    App\Vendoring\VendoringBundle::class => ['all' => true],
    App\Viewing\ViewingBundle::class => ['all' => true],
    App\Analysing\AnalysingBundle::class => ['all' => true],
    App\Delivering\DeliveringBundle::class => ['all' => true],
    App\Ordering\OrderingBundle::class => ['all' => true],
    App\Projecting\ProjectingBundle::class => ['all' => true],
    Scheb\TwoFactorBundle\SchebTwoFactorBundle::class => ['all' => true],
];
