<?php

declare(strict_types=1);

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
    Symfony\UX\Turbo\TurboBundle::class => ['all' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    App\Administering\AdministeringBundle::class => ['all' => true],
    App\Addressing\AddressingBundle::class => ['all' => true],
    Scheb\TwoFactorBundle\SchebTwoFactorBundle::class => ['all' => true],
    App\Retailing\RetailingBundle::class => ['all' => true],
    App\Attaching\AttachingBundle::class => ['all' => true],
    App\Messaging\MessagingBundle::class => ['all' => true],
    App\Notifying\NotifyingBundle::class => ['all' => true],
    App\Streaming\StreamingBundle::class => ['all' => true],
    App\Carting\CartingBundle::class => ['dev' => true, 'test' => true],
    App\Ordering\OrderingBundle::class => ['all' => true],
    App\Shipping\ShipmentBundle::class => ['all' => true],
    App\Paying\PayingBundle::class => ['all' => true],
    App\Walleting\WalletingBundle::class => ['all' => true],
    App\Withdrawing\WithdrawingBundle::class => ['all' => true],
    App\Locating\LocatingBundle::class => ['all' => true],
];
